/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti13.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      13                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  13                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\songti13.txt     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti13;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0030[ 13] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0031[ 13] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ___X____,
  __XX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0032[ 13] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X___X__,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0033[ 13] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  __XXX___,
  _X___X__,
  _____X__,
  _____X__,
  ___XX___,
  _____X__,
  _____X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0034[ 13] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ____X___,
  ____X___,
  ___XX___,
  __X_X___,
  __X_X___,
  _X__X___,
  _XXXXX__,
  ____X___,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0035[ 13] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  _XXXXX__,
  _X______,
  _X______,
  _XXXX___,
  _X___X__,
  _____X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0036[ 13] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X______,
  _X_XX___,
  _XX__X__,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0037[ 13] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0038[ 13] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0039[ 13] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__XX__,
  __XX_X__,
  _____X__,
  _X__X___,
  __XX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0041[ 13] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ___X____,
  ___X____,
  __X_X___,
  __X_X___,
  __X_X___,
  __XXX___,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_0042[ 13] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  XXXXX___,
  ________,
  ________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_6BCD[ 26] = { /* code 6BCD */
  ________,________,
  __XXXXXX,XXX_____,
  __X_____,__X_____,
  __X___X_,__X_____,
  __X____X,__X_____,
  _XXXXXXX,XXXX____,
  __X_____,__X_____,
  __X__X__,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXXX____,
  ________,__X_____,
  _______X,XX______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti13_7EBF[ 26] = { /* code 7EBF */
  ___X____,X_X_____,
  ___X____,X__X____,
  __X_____,XXXX____,
  _X__X_XX,X_______,
  _XXX____,X_______,
  ___X____,XXXX____,
  __X___XX,X_______,
  _XXXX___,X_X_____,
  ________,XX______,
  ___XX___,X__X____,
  _XX____X,_X_X____,
  _____XX_,__XX____,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsongti13_CharInfo[14] = {
   {   7,   7,  1, acGUI_Fontsongti13_0030 } /* code 0030 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0031 } /* code 0031 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0032 } /* code 0032 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0033 } /* code 0033 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0034 } /* code 0034 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0035 } /* code 0035 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0036 } /* code 0036 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0037 } /* code 0037 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0038 } /* code 0038 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0039 } /* code 0039 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0041 } /* code 0041 */
  ,{   7,   7,  1, acGUI_Fontsongti13_0042 } /* code 0042 */
  ,{  13,  13,  2, acGUI_Fontsongti13_6BCD } /* code 6BCD */
  ,{  13,  13,  2, acGUI_Fontsongti13_7EBF } /* code 7EBF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti13_Prop4 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_Fontsongti13_CharInfo[ 13] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti13_Prop3 = {
   0x6BCD /* first character */
  ,0x6BCD /* last character  */
  ,&GUI_Fontsongti13_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontsongti13_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti13_Prop2 = {
   0x0041 /* first character */
  ,0x0042 /* last character  */
  ,&GUI_Fontsongti13_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontsongti13_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsongti13_Prop1 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fontsongti13_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti13_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti13 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,13 /* height of font  */
  ,13 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti13_Prop1}
  ,11 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

