/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include.h"
#include "sys_Variable.h"
#include "app_Optimset.h"
#include "string.h"
 
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_TEXT_0    (GUI_ID_USER + 0x05)
#define ID_TEXT_1    (GUI_ID_USER + 0x06)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
extern WM_HWIN hPage[25];
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti15;
static const GUI_WIDGET_CREATE_INFO _Now_Alarm[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 20, 480, 209, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Help", ID_BUTTON_0, 410, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_1, 342, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "History_Alarm", ID_BUTTON_2, 274, 236, 67, 23, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_0, 428,259, 45, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 360, 259, 55, 15, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/**
  *@brief  报警描述解析
	*@param  event
	*        type
	*        CHbuf
	*@retval NONE
	*@nopte  NONE
	*/
void gAlm_InfoAnalyze(const enum AlmEventTypeDef event, const enum AlmTypeDef type, char *CHbuf)
{		
     uint8_t i;
     char buf[25];
		 
		 /* 母线报警描述 */
		 if(event <= eAlmEvent_BSPD )
		 {					    
				 switch(event%10)
				 {
							 case eAlmEvent_AUa:     /* A母线A相电压告警 */
										/* 下限*/
										if(type == eAlmType_Under)
										{
												memcpy(buf,"母线A相欠压",30); 
										}
										/* 上限 */
										else if (type == eAlmType_Over)
										{
												memcpy(buf,"母线A相过压",30); 
										}								 
										break;
							 case eAlmEvent_AUb:     /* A母线B相电压告警 */
										/* 下限 */
										if(type == eAlmType_Under)
										{
												 memcpy(buf,"母线B相欠压",30);																	
										}
										/* 上限 */
										else if (type == eAlmType_Over)
										{
												 memcpy(buf,"母线B相过压",30);
										}											      
										break;
							 case eAlmEvent_AUc:     /* A母线C相电压告警 */
										/* 下限 */
										if(type == eAlmType_Under)
										{
												memcpy(buf,"母线C相欠压",30);																	
										}
										/* 上限 */
										else if (type == eAlmType_Over)
										{
												memcpy(buf,"母线C相过压",30);
										}
										break;
							 case eAlmEvent_AIa:     /* A母线A相电流告警 */
										/* 一级 */
										if(type == eAlmType_Over)
										{
												memcpy(buf,"母线A相一级过流",30);																	
										}
										/* 二级*/
										else if (type == eAlmType_OverSec)
										{
												memcpy(buf,"母线A相二级过流",30);
										}
										break;
							 case eAlmEvent_AIb:     /* A母线B相电流告警 */
										/* 一级 */
										if(type == eAlmType_Over)
										{
												memcpy(buf,"母线B相一级过流",30);																	
										}
										/* 二级*/
										else if (type == eAlmType_OverSec)
										{
												memcpy(buf,"母线B相二级过流",30);
										}
										break;
							 case eAlmEvent_AIc:     /*A母线C相电流告警*/
										/* 一级 */
										if(type == eAlmType_Over)
										{
												memcpy(buf,"母线C相一级过流",30);																	
										}
										/* 二级 */
										else if (type == eAlmType_OverSec)
										{
												memcpy(buf,"母线C相二级过流",30);
										}
										break;
							 case eAlmEvent_AP:     /* A母线功率告警 */
										if(type == eAlmType_Over)
										{
												memcpy(buf,"母线总功率越限",30);																	
										}
										break;
							 case eAlmEvent_AF:     /*A母线频率告警  */
										/* 下限 */
										if(type == eAlmType_Under)
										{
												memcpy(buf,"母线欠频",30);																	
										}
										/* 上限 */
										else if (type == eAlmType_Over)
										{
												memcpy(buf,"母线过频",30);
										}
										break;
							 case eAlmEvent_AQF:     /* A母线开关告警 */
										if(type == eAlmType_IOTrip)
										{
												memcpy(buf,"母线开关故障",30);																	
										}
										break;
							 case eAlmEvent_ASPD:    /*A母线防雷告警 */
										if(type == eAlmType_IOTrip)
										{
												memcpy(buf,"母线防雷故障",30);
										}
										break;
							 default: break;
				 }  
				 if(Optimset_st.Setup.Setup_st.bBusMode == BusModeS) 
				 {
						 /* A母线 */
						 if((event/10) == 0)
						 {
								 sprintf(CHbuf,"A%s", buf);
						 }
						 /* B母线 */
						 else
						 {
								 sprintf(CHbuf,"B%s", buf);
						 }
					
				 }
				 else if(Optimset_st.Setup.Setup_st.bBusMode == BusModeY)
				 {
					 
					 	 /* A母线 */
						 if((event/10) == 0)
						 {
								 sprintf(CHbuf,"A%s", buf);
						 }
						 /* B母线 */
						 else
						 {
								 sprintf(CHbuf,"B%s", buf);
						 }
						 if(event == eAlmEvent_AQF)
						 {
				         sprintf(CHbuf,"%s", buf); 
						 }
				 }
				 else
				 {
				     sprintf(CHbuf,"%s", buf); 
				 }
		 }
		 /* 支路开关状态告警描述 A路 0x80-0xC7 B路 0xC8-0x10F */
		 else if(event >= eAlmEvent_SW)
		 { 
				 /*双路模式*/
				 if(Optimset_st.Setup.Setup_st.bBusMode == BusModeS)
				 {
						/* A支路开关 */
						if(event < (eAlmEvent_SW+71))
						{
								memcpy(CHbuf, "A", 1);
								memcpy(CHbuf + 1, "支路", 6);
								i = event-(eAlmEvent_SW - 1);
								sprintf(buf,"%0.2d", i);
								memcpy(CHbuf + 7, buf, 2);
								memcpy(CHbuf + 9, "开关故障", 12);										
						}
						/* B支路开关 */
						else
						{
								memcpy(CHbuf, "B", 1);
								memcpy(CHbuf + 1, "支路", 6);
								i = event-(eAlmEvent_SW + 71);
								sprintf(buf,"%0.2d", i);
								memcpy(CHbuf + 7, buf, 2);
								memcpy(CHbuf + 9, "开关故障", 12);	
						}
				 }
				 /* 其他模式 */
				 else
				 {
								memcpy(CHbuf, "支路", 6);
								i = event-(eAlmEvent_SW - 1);
								sprintf(buf,"%0.3d", i);
								memcpy(CHbuf + 6, buf, 3);
								memcpy(CHbuf + 9, "开关故障", 12);	
				 }							 
		 }					   
}


static void nAlm_Display(GUI_HWIN hItem)
{
   int8_t i, j;
   char buf[30];

   if(RTAlmIndex > 0)
	 {
	     for(i = RTAlmIndex-1; i >= 0; i--)
			 {
					 /* 告警产生：红色字体， 告警结束：蓝色字体 */
					 if(gRTAlmRecord[i].flag == TerminateFlag)
					 {
					 
					     /* 告警结束时间 */
						   sprintf(buf,"%0.2d/%0.2d/%0.2d %0.2d:%0.2d:%0.2d",gRTAlmRecord[i].TerminateYear,
											 gRTAlmRecord[i].TerminateMonth, gRTAlmRecord[i].TerminateDate,
											 gRTAlmRecord[i].TerminateHour, gRTAlmRecord[i].TerminateMiniute, 
											 gRTAlmRecord[i].TerminateSecond);	
							 LISTVIEW_SetItemText(hItem,0,RTAlmIndex-1-i,buf);
							 
					     LISTVIEW_SetItemText(hItem,1,RTAlmIndex-1-i,"报警结束");
							 for(j = 0; j < 5; j++)
							 {
							     LISTVIEW_SetItemTextColor(hItem,j,RTAlmIndex-1-i,LISTVIEW_CI_UNSEL,GUI_BLUE);	
							 }   						 
					 }
					 else
					 {
							 /* 告警产生时间 */
						 sprintf(buf,"%0.2d/%0.2d/%0.2d %0.2d:%0.2d:%0.2d", gRTAlmRecord[i].GenerateYear,
											 gRTAlmRecord[i].GenerateMonth, gRTAlmRecord[i].GenerateDate,                      
											 gRTAlmRecord[i].GenerateHour, gRTAlmRecord[i].GenerateMiniute, 										
											 gRTAlmRecord[i].GenerateSecond);	
							 LISTVIEW_SetItemText(hItem,0,RTAlmIndex-1-i,buf);
							 LISTVIEW_SetItemText(hItem,1,RTAlmIndex-1-i,"报警产生");
							 for(j = 0; j < 5; j++)
							 {
									 LISTVIEW_SetItemTextColor(hItem,j,RTAlmIndex-1-i,LISTVIEW_CI_UNSEL,GUI_RED);	
							 } 
					 }
					 
					 /* 当前值 */
					 sprintf(buf, "%.2f", gRTAlmRecord[i].fCurrentValue);
					 LISTVIEW_SetItemText(hItem,2,RTAlmIndex-1-i,buf);
					 
					 /* 界限值 */
					 sprintf(buf, "%d", gRTAlmRecord[i].usThresholdValue);
					 LISTVIEW_SetItemText(hItem,3,RTAlmIndex-1-i,buf);	

           /* 报警描述 */
					 gAlm_InfoAnalyze(gRTAlmRecord[i].AlmEvent, gRTAlmRecord[i].AlmType, buf);
           LISTVIEW_SetItemText(hItem,4,RTAlmIndex-1-i,buf);					 
			 }
	 }     
}

static void _cbNowAlarm(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
	  LISTVIEW_SetHeaderHeight(hItem, 23);
		LISTVIEW_SetBkColor(hItem,LISTVIEW_CI_SEL,GUI_WHITE);
	  HEADER_SetTextColor(LISTVIEW_GetHeader(hItem),GUI_BLUE_98);
    HEADER_SetFont(LISTVIEW_GetHeader(hItem),&GUI_Fontsongti15);
    LISTVIEW_AddColumn(hItem, 150, "时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 70, "报警事件", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, "当前值", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, "界限值", GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_AddColumn(hItem, 140, "报警描述", GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetRowHeight(hItem,19);
		LISTVIEW_SetFont(hItem,&GUI_Fontsongti15);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"帮助");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"返回");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"历史报警");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    break;
		
		case WM_PAINT: 
			GUI_SetColor(GUI_LIGHTBLUE);
			GUI_FillRect(0,0,480,19);
		  GUI_SetColor(GUI_LIGHTBLUE);
		  GUI_FillRect(0,260,480,272);
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			if(Optimset_st.Setup.Setup_st.bBusMode==2) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",100,3);
		  if(Optimset_st.Setup.Setup_st.bBusMode==1) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",100,3);
		  if(Optimset_st.Setup.Setup_st.bBusMode==8) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",100,3);
		  if(Optimset_st.Setup.Setup_st.bBusMode==4) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",100,3);
	
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Font13_1);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			GUI_DispStringAt(SoftVersion,5,4);
			
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			GUI_DispStringAt("实时报警",400,3);
		break;
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Help'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				 Window_Help_call=0x09;
			   WM_DeleteWindow(hPage[10]);
				 hPage[20]= CreateWindow_Help(WM_HBKWIN);
				 WM_ShowWindow(hPage[20]);
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				  WM_DeleteWindow(hPage[10]);
          hPage[0]=CreateWindowHome(WM_HBKWIN);
		      WM_ShowWindow(hPage[0]);
        break;
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'History_Alarm'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				   WM_DeleteWindow(hPage[10]);
				   hPage[11] = CreateWindowHistoryAlarm(WM_HBKWIN);
           WM_ShowWindow(hPage[11]);    
        break;
      }
      break;
    }
    break;
	case WM_TIMER:
			 Caculate_RTC(pMsg,ID_TEXT_1,ID_TEXT_0);	
			 
			 nAlm_Display(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
			 
	     WM_RestartTimer(pMsg->Data.v, 1000);
	  break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindowNowAlarm(WM_HWIN hParent);
WM_HWIN CreateWindowNowAlarm(WM_HWIN hParent) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_Now_Alarm, GUI_COUNTOF(_Now_Alarm), _cbNowAlarm, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,100,0);
  return hWin;
}

/*************************** End of file ****************************/
