/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include.h"
#include "bsp_Fram.h"
#include "sys_FramAlloc.h"
#include "sys_Variable.h"
#include "app_Optimset.h"
#include "cmsis_os.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x01)
#define ID_LISTVIEW_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_0    (GUI_ID_USER + 0x03)
#define ID_BUTTON_1    (GUI_ID_USER + 0x04)
#define ID_BUTTON_2    (GUI_ID_USER + 0x05)
#define ID_BUTTON_3    (GUI_ID_USER + 0x06)
#define ID_BUTTON_4    (GUI_ID_USER + 0x07)
#define ID_TEXT_0      (GUI_ID_USER + 0x08)
#define ID_TEXT_1      (GUI_ID_USER + 0x09)
#define ID_TEXT_2      (GUI_ID_USER + 0x0A)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _History_Alarm[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 21, 480, 209, 0, 0x00, 0 },
  { BUTTON_CreateIndirect, "Next_Page", ID_BUTTON_0, 273, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Refresh", ID_BUTTON_1, 137, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Last_Page", ID_BUTTON_2, 205, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_3, 342, 236, 68, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Help", ID_BUTTON_4, 411, 236, 67, 23, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_0, 428,259, 45, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 360, 259, 55, 15, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_2, 225, 259, 53, 15, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
extern WM_HWIN hPage[25];
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti15;


static AlmRecordTypeDef      nPTAlmRecord;

static void Alm_Display(GUI_HWIN hItem, uint8_t row)
{
   char buf[30]={0};
   LISTVIEW_SetFont(hItem,&GUI_Fontsongti15);
	 /* 告警产生日期 */
	 sprintf(buf,"%0.2d/%0.2d/%0.2d", 
					 nPTAlmRecord.GenerateYear,
					 nPTAlmRecord.GenerateMonth, 
					 nPTAlmRecord.GenerateDate);	
	 LISTVIEW_SetItemText(hItem,0,row,buf);
	 
	 /* 告警产生时间 */
	 sprintf(buf,"%0.2d:%0.2d:%0.2d", 
					 nPTAlmRecord.GenerateHour, 
					 nPTAlmRecord.GenerateMiniute, 										
					 nPTAlmRecord.GenerateSecond);	
	 LISTVIEW_SetItemText(hItem,1,row,buf);
													 
	 /* 当前值 */
	 sprintf(buf, "%.2f", nPTAlmRecord.fCurrentValue);
	 LISTVIEW_SetItemText(hItem,2,row,buf);
	 

	 /* 报警描述 */
	 gAlm_InfoAnalyze(nPTAlmRecord.AlmEvent,  nPTAlmRecord.AlmType, buf);
	 LISTVIEW_SetItemText(hItem,3,row,buf);

	 /* 有告警结束标志，显示告警结束时间， 否则不显示 */
	 if(nPTAlmRecord.flag == TerminateFlag)
	 {					 
			 /* 告警结束时间 */
			 sprintf(buf,"%0.2d/%0.2d/%0.2d %0.2d:%0.2d:%0.2d", nPTAlmRecord.TerminateYear,
							 nPTAlmRecord.TerminateMonth, nPTAlmRecord.TerminateDate,
							 nPTAlmRecord.TerminateHour, nPTAlmRecord.TerminateMiniute, 
							 nPTAlmRecord.TerminateSecond);	
			 LISTVIEW_SetItemText(hItem,4,row,buf); 						 
	 }
     else
	 {
	     LISTVIEW_SetItemText(hItem,4,row,""); 
	 }		 
}


static void nAlmRecord_Get(GUI_HWIN hItem, uint8_t page)
{
   uint8_t row;
   int16_t i;
	 uint16_t usFM_OperateAddr;
	 
   if(gPTAlmRelate.AlmIndex%RTAlm_Item == 0)
	 {
			 for(i = gPTAlmRelate.AlmIndex-1-page*RTAlm_Item; i >= gPTAlmRelate.AlmIndex-RTAlm_Item-page*RTAlm_Item; i--)
			 {
					 /* 获取历史告警0~gPTAlmRelate.AlmIndex条 */
					 usFM_OperateAddr = FMAddr_PastAlm + FMOffset_AlmRecord + i * sizeof(nPTAlmRecord);
						 
					 taskENTER_CRITICAL();
					 Fram_I2C_Read((uint8_t *)&nPTAlmRecord, usFM_OperateAddr, sizeof(nPTAlmRecord));		
					 taskEXIT_CRITICAL();
					 row = gPTAlmRelate.AlmIndex-1-page*RTAlm_Item-i;
           Alm_Display(hItem, row);					 
			 }
			 
			 /* 若满500条，则处理 gPTAlmRelate.AlmIndex到500的记录*/
			 if((gPTAlmRelate.FullFlag != 0x00) && (page >= gPTAlmRelate.AlmIndex/RTAlm_Item))
			 {
					 for(i = PTAlm_Item-1-(page-gPTAlmRelate.AlmIndex/RTAlm_Item)*RTAlm_Item; 
					     i >= PTAlm_Item-RTAlm_Item-(page-gPTAlmRelate.AlmIndex/RTAlm_Item)*RTAlm_Item; i--)
					 {
							 /* 获取历史告警 */
							 usFM_OperateAddr = FMAddr_PastAlm + FMOffset_AlmRecord + i * sizeof(nPTAlmRecord);
								 
							 taskENTER_CRITICAL();
							 Fram_I2C_Read((uint8_t *)&nPTAlmRecord, usFM_OperateAddr, sizeof(nPTAlmRecord));		
							 taskEXIT_CRITICAL();
							 row = PTAlm_Item-1-(page-gPTAlmRelate.AlmIndex/RTAlm_Item)*RTAlm_Item-i;
               Alm_Display(hItem, row);							 
					 }   
			 }
	 }
   else
	 {
	     /* 整页显示0~gPTAlmRelate.AlmIndex的记录 */
			 if(page < gPTAlmRelate.AlmIndex/RTAlm_Item)
			 {
					 for(i = gPTAlmRelate.AlmIndex-1-page*RTAlm_Item; i >= gPTAlmRelate.AlmIndex-RTAlm_Item-page*RTAlm_Item; i--)
					 {
							 usFM_OperateAddr = FMAddr_PastAlm + FMOffset_AlmRecord + i * sizeof(nPTAlmRecord);
								 
							 taskENTER_CRITICAL();
							 Fram_I2C_Read((uint8_t *)&nPTAlmRecord, usFM_OperateAddr, sizeof(nPTAlmRecord));		
							 taskEXIT_CRITICAL();
							 row = gPTAlmRelate.AlmIndex-1-page*RTAlm_Item-i;
							 Alm_Display(hItem, row);					 
					 }
			 }
			 /*历史告警0~gPTAlmRelate.AlmIndex取余及gPTAlmRelate.AlmIndex~PTAlm_Item */
			 else
			 {
			    /* 显示 0~gPTAlmRelate.AlmIndex余下不满RTAlm_Item的记录*/
			    if(gPTAlmRelate.FullFlag == 0x00)
					{
					    for(i = (gPTAlmRelate.AlmIndex - 1)%RTAlm_Item;i >= 0;i--)
							{
									 usFM_OperateAddr = FMAddr_PastAlm + FMOffset_AlmRecord + i * sizeof(nPTAlmRecord);
										 
									 taskENTER_CRITICAL();
									 Fram_I2C_Read((uint8_t *)&nPTAlmRecord, usFM_OperateAddr, sizeof(nPTAlmRecord));		
									 taskEXIT_CRITICAL();
									 row = (gPTAlmRelate.AlmIndex - 1)%RTAlm_Item-i;
									 Alm_Display(hItem, row);	
							}
							if(page == gPTAlmRelate.AlmIndex/RTAlm_Item)
							{
									for(i=(gPTAlmRelate.AlmIndex - 1)%RTAlm_Item+1; i<10; i++)
									{
											LISTVIEW_SetItemText(hItem,0,i,"");
											LISTVIEW_SetItemText(hItem,1,i,"");
											LISTVIEW_SetItemText(hItem,2,i,"");
											LISTVIEW_SetItemText(hItem,3,i,"");
											LISTVIEW_SetItemText(hItem,4,i,"");
									}
							}
					}
					else
					{   
					    /* 显示 0~gPTAlmRelate.AlmIndex余下不满RTAlm_Item的记录*/
					    for(i = (gPTAlmRelate.AlmIndex - 1)%RTAlm_Item;i >= 0;i--)
							{
									 usFM_OperateAddr = FMAddr_PastAlm + FMOffset_AlmRecord + i * sizeof(nPTAlmRecord);
										 
									 taskENTER_CRITICAL();
									 Fram_I2C_Read((uint8_t *)&nPTAlmRecord, usFM_OperateAddr, sizeof(nPTAlmRecord));		
									 taskEXIT_CRITICAL();
									 row = (gPTAlmRelate.AlmIndex - 1)%RTAlm_Item-i;
									 Alm_Display(hItem, row);	
							}
							/* 用 gPTAlmRelate.AlmIndex~PTAlm_Item的记录补满该页*/
              for(i = PTAlm_Item-1; i >= PTAlm_Item-(RTAlm_Item-gPTAlmRelate.AlmIndex%RTAlm_Item); i--)
					    {
									 usFM_OperateAddr = FMAddr_PastAlm + FMOffset_AlmRecord + i * sizeof(nPTAlmRecord);
										 
									 taskENTER_CRITICAL();
									 Fram_I2C_Read((uint8_t *)&nPTAlmRecord, usFM_OperateAddr, sizeof(nPTAlmRecord));		
									 taskEXIT_CRITICAL();
									 row = (PTAlm_Item - 1)-i;
									 Alm_Display(hItem, row);							 
					    }
							/* 整页显示gPTAlmRelate.AlmIndex~PTAlm_Item的记录*/
						  if(page >= gPTAlmRelate.AlmIndex/RTAlm_Item + 1)
						  {
								 for(i = PTAlm_Item-1-(page-(gPTAlmRelate.AlmIndex/RTAlm_Item+1))*RTAlm_Item; 
										 i >= PTAlm_Item-RTAlm_Item-(page-(gPTAlmRelate.AlmIndex/RTAlm_Item+1))*RTAlm_Item; i--)
								 {
										 usFM_OperateAddr = FMAddr_PastAlm + FMOffset_AlmRecord + i * sizeof(nPTAlmRecord);
											 
										 taskENTER_CRITICAL();
										 Fram_I2C_Read((uint8_t *)&nPTAlmRecord, usFM_OperateAddr, sizeof(nPTAlmRecord));		
										 taskEXIT_CRITICAL();
										 row = PTAlm_Item-1-(page-(gPTAlmRelate.AlmIndex/RTAlm_Item+1))*RTAlm_Item-i;
										 Alm_Display(hItem, row);							 
								 }   
						  }							
					}
			 } 
	 }
}


static void _cbWindow_HistoryAlarm(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	static  uint8_t page = 0,MaxPage=0;
	char buf[10];
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		LISTVIEW_SetHeaderHeight(hItem, 23);
	  LISTVIEW_SetBkColor(hItem,LISTVIEW_CI_SEL,GUI_WHITE);
		HEADER_SetTextColor(LISTVIEW_GetHeader(hItem),GUI_BLUE_98);
    HEADER_SetFont(LISTVIEW_GetHeader(hItem),&GUI_Fontsongti15);
    LISTVIEW_AddColumn(hItem, 74, "日期", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 74, "时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 58, "当前值", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 126, "报警描述", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_AddColumn(hItem, 148, "结束时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetRowHeight(hItem,19);
		LISTVIEW_SetFont(hItem,&GUI_Fontsongti15);
		for(int i=0;i<10;i++)
		{
			LISTVIEW_DisableRow(hItem,i);
			for(int j=0;j<5;j++)
			{
				LISTVIEW_SetItemTextColor(hItem,j,i,LISTVIEW_CI_UNSEL,GUI_BLACK);
				LISTVIEW_SetItemBkColor(hItem,j,i,LISTVIEW_CI_DISABLED,GUI_WHITE);
			}
		}
		LISTVIEW_SetDefaultBkColor(LISTVIEW_CI_UNSEL,GUI_WHITE);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"清除报警");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"上一页");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"下一页");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
		BUTTON_SetText(hItem,"返回");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
		BUTTON_SetText(hItem,"帮助");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    break;
		
		case WM_PAINT: 
			GUI_SetColor(GUI_LIGHTBLUE);
			GUI_FillRect(0,0,480,20);
		  GUI_SetColor(GUI_LIGHTBLUE);
		  GUI_FillRect(0,260,480,272);
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",100,3);
		  if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",100,3);
		  if(Optimset_st.Setup.Setup_st.bBusMode==BusModeY) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",100,3);
		  if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",100,3);
	
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Font13_1);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			GUI_DispStringAt(SoftVersion,5,4);
			
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			GUI_DispStringAt("历史报警信息",380,3);
			if(gPTAlmRelate.FullFlag == 0x01)
			{
			  MaxPage=50;				
		  }
			else
			{
			   if(gPTAlmRelate.AlmIndex%10==0)	
			      MaxPage = gPTAlmRelate.AlmIndex/10;
			   else MaxPage = gPTAlmRelate.AlmIndex/10+1;
			}

     	nAlmRecord_Get(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), page);
			
			if(gPTAlmRelate.AlmIndex==0)
			{
				 page=0;
				 MaxPage=1;
				for(int i=0;i<10;i++)
				{
					for(int j=0;j<6;j++)
					{
						LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),j,i,"");
					}
				}
		  }
			
			sprintf(buf,"%d / %d",page+1,MaxPage);
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_2),buf);
			TEXT_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_TEXT_2),GUI_WHITE);
		break;
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	  switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				switch(Id) {
					case ID_BUTTON_0: // Notifications sent by 'Next_Page'
							if(page < MaxPage-1)
							{
									page ++;													
							}
							 WM_InvalidateWindow(pMsg->hWin);
				    break;
					case ID_BUTTON_1: // Notifications sent by 'Refresh'
						if(User_login==0x00)
						{
					     Window_Call_Keypad=0x08;
							 hPage[12] = CreateWindowKeypad(hPage[11]);
							 WM_ShowWindow(hPage[12]);
						}
						else
						{
							Alm_RecordClear();
						  WM_InvalidateWindow(pMsg->hWin);
						}
						break;
					case ID_BUTTON_2: // Notifications sent by 'Last_Page'
							if(page > 0)				 
									page -= 1;	
							WM_InvalidateWindow(pMsg->hWin);
						break;
					case ID_BUTTON_3: // Notifications sent by 'Back'
						  WM_DeleteWindow(hPage[11]);
						  hPage[10] = CreateWindowNowAlarm(WM_HBKWIN);
						  WM_ShowWindow(hPage[10]);
						break;
				  case ID_BUTTON_4: // Notifications sent by 'Help'
					  	Window_Help_call=0x10;
						  WM_DeleteWindow(hPage[11]);
						  hPage[20]= CreateWindow_Help(WM_HBKWIN);
					    WM_ShowWindow(hPage[20]);
						break;
				}
				break;
			}
			break;
	case WM_TIMER:					
		 Caculate_RTC(pMsg,ID_TEXT_1,ID_TEXT_0);	
    		
	   WM_RestartTimer(pMsg->Data.v, 100);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindowHistoryAlarm(WM_HWIN hParent);
WM_HWIN CreateWindowHistoryAlarm(WM_HWIN hParent) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_History_Alarm, GUI_COUNTOF(_History_Alarm), _cbWindow_HistoryAlarm, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,200,0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
