/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include.h"
#include "app_Optimset.h"
#include "app_Acquisition.h"
#include "app_PTEnergy.h"
#include "sys_Variable.h"
#include "gui.h"
#include "stdio.h"
#include "stdint.h"
#include <stdlib.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_DROPDOWN_0    (GUI_ID_USER + 0x03)
#define ID_TEXT_0    (GUI_ID_USER + 0x04)
#define ID_TEXT_1    (GUI_ID_USER + 0x05)
#define ID_EDIT_0    (GUI_ID_USER + 0x06)
#define ID_BUTTON_0    (GUI_ID_USER + 0x07)
#define ID_BUTTON_1    (GUI_ID_USER + 0x08)
#define ID_BUTTON_2    (GUI_ID_USER + 0x09)
#define ID_BUTTON_3    (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4    (GUI_ID_USER + 0x0B)
#define ID_BUTTON_5    (GUI_ID_USER + 0x0C)
#define ID_BUTTON_6    (GUI_ID_USER + 0x0D)
#define ID_BUTTON_7    (GUI_ID_USER + 0x0E)
#define ID_BUTTON_8    (GUI_ID_USER + 0x0F)
#define ID_BUTTON_9    (GUI_ID_USER + 0x10)
#define ID_BUTTON_15    (GUI_ID_USER + 0x11)
#define ID_BUTTON_11    (GUI_ID_USER + 0x12)
#define ID_BUTTON_12    (GUI_ID_USER + 0x13) 
#define ID_BUTTON_13    (GUI_ID_USER + 0x14) 
#define ID_BUTTON_14    (GUI_ID_USER + 0x15)
#define ID_BUTTON_10    (GUI_ID_USER + 0x16)
#define ID_TEXT_2    (GUI_ID_USER + 0x17)
#define ID_TEXT_3    (GUI_ID_USER + 0x18)
#define ID_EDIT_1    (GUI_ID_USER + 0x19)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
extern WM_HWIN hPage[25];
int _aKey[] = {GUI_KEY_DELETE,GUI_KEY_LEFT, GUI_KEY_RIGHT};
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti15;
static const GUI_WIDGET_CREATE_INFO _KeypadUserCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 80, 30, 290, 160, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 108, 25, 110, 35, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "UserName", ID_TEXT_0, 58, 27, 50, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PassWord_Text", ID_TEXT_1, 58, 57, 50, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "PassWord", ID_EDIT_0, 108, 55, 110, 20, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "1", ID_BUTTON_0, 10, 90, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_1, 40, 90, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_2, 70, 90, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_3, 100, 90, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_4, 130, 90, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_5, 160, 90, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_6, 10, 120, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_7, 40, 120, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_8, 70, 120, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_9, 100, 120, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_10, 220, 120, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Del", ID_BUTTON_11, 250, 90, 30, 30, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "<-", ID_BUTTON_12, 190, 90, 30, 30, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "->", ID_BUTTON_13, 220, 90, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_14, 160, 120, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ".", ID_BUTTON_15, 130, 120, 30, 30, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_2,100 , 76, 100, 15, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};


static const GUI_WIDGET_CREATE_INFO _NumberpadCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 5, 50, 120, 180, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_0, 10, 10, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_1, 45, 10, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_2, 80, 10, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_3, 10, 45, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_4, 45, 45, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_5, 80, 45, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_6, 10, 80, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_7, 45, 80, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_8, 80, 80, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_9, 10, 115, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_10, 62, 150, 47, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Del", ID_BUTTON_11, 80, 115, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_14, 10, 150, 47, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ".", ID_BUTTON_15, 45, 115, 30, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

static const GUI_WIDGET_CREATE_INFO _Energy_ClearCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 190, 100, 110, 65, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "1", ID_BUTTON_0, 10, 30, 25, 25 ,0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_1, 70, 30, 25, 25, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

static const GUI_WIDGET_CREATE_INFO _Change_Password[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 80, 30, 290,210, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 108, 25, 110, 35, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "UserName", ID_TEXT_0, 58, 27, 50, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Old_PassWord_Text", ID_TEXT_1, 58, 57, 50, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Old_PassWord", ID_EDIT_0, 108, 55, 110, 20, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "1", ID_BUTTON_0, 10, 140, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_1, 40, 140, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_2, 70, 140, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_3, 100, 140, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_4, 130, 140, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_5, 160, 140, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_6, 10, 170, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_7, 40, 170, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_8, 70, 170, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_9, 100, 170, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_10, 220, 170, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Del", ID_BUTTON_11, 250, 140, 30, 30, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "<-", ID_BUTTON_12, 190, 140, 30, 30, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "->", ID_BUTTON_13, 220, 140, 30, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_14, 160, 170, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ".", ID_BUTTON_15, 130, 170, 30, 30, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "User", ID_TEXT_3,108, 25, 110, 35, 0, 0x0, 0},
	{ TEXT_CreateIndirect, "New_PassWord_Text", ID_TEXT_2, 58, 87, 50, 20, 0, 0x0, 0},
	{ EDIT_CreateIndirect, "New_PassWord", ID_EDIT_1, 108, 85, 110, 20, 0, 0x0, 0},
 
};

static const GUI_WIDGET_CREATE_INFO _Userlogin_Clear[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 190, 100, 110, 65, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "1", ID_BUTTON_0, 10, 30, 25, 25 ,0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_1, 70, 30, 25, 25, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

uint8_t User_login=0;
uint8_t Window_Call_Keypad=0;
static void _cbKeypad(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int     i;
  int     Pressed=0;
	int     PassWord=0xFF;
	int DropdownSecItemNum=0;
  static int PassWord_Error=0;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetFont(hItem,&GUI_Fontsongti15);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem,&GUI_Fontsongti15);
    TEXT_SetText(hItem, "用户名");
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem,&GUI_Fontsongti15);
    TEXT_SetText(hItem, "密码");
	
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		DROPDOWN_SetFont(hItem,&GUI_Fontsongti15);
    DROPDOWN_AddString(hItem, "负责人"); 
		DROPDOWN_AddString(hItem, "厂家");
    for (i = 0; i <16; i++)
		{
      hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0+i);
			BUTTON_SetFont(hItem, GUI_FONT_16_1);
      BUTTON_SetFocussable(hItem, 0); 	
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		}
		  hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);  /* Get the handle of the edit widget */
      EDIT_SetText(hItem, "");                   /* Set text */
			EDIT_SetFocussable(hItem,1);
    break;
	case WM_PAINT:
			GUI_SetColor(GUI_LIGHTBLUE);
			GUI_FillRect(0,0,295,19);
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			GUI_DispStringAt("用户登录",5,4);
			if(PassWord_Error==1)
			{
				hItem=WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
				TEXT_SetText(hItem,"PassWord Error");
				TEXT_SetTextColor(hItem,GUI_RED);		
			}
				break;
			
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (NCode) {
    case WM_NOTIFICATION_CLICKED:
      Pressed = 1;
    case WM_NOTIFICATION_RELEASED:
      if ((Id >= GUI_ID_USER + 7) && (Id <=GUI_ID_USER + 0x14)) 
			{
        int Key;
        if ((Id >= GUI_ID_USER + 7)&&(Id < GUI_ID_USER + 0x12))  
				{
          char acBuffer[11];
          BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); /* Get the text of the button */
          Key = acBuffer[0];
        } 
				else 
				{
          Key = _aKey[Id - GUI_ID_USER -  0x12];                        /* Get the text from the array */
        }
        GUI_SendKeyMsg(Key, Pressed);                                /* Send a key message to the focussed window */
      }
		if(Id==ID_EDIT_0)
		{
		switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				 WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));	
        break;
      }
		}		
		if (Id==ID_BUTTON_14)// Notifications sent by 'OK'
		{
			switch(NCode) {
       case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
          DropdownSecItemNum=DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0));
			    char buf[5];
				  EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), buf, sizeof(buf));
			    PassWord = atoi(buf); 
			if((DropdownSecItemNum==0)&&(PassWord==UsrPassword))
			{
					User_login=0xFF; 
				if(Window_Call_Keypad==0x02)
				{
					Acq_MAXClear();
				  WM_DeleteWindow(hPage[12]);
				  hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
					WM_ShowWindow(hPage[18]);
				}
				else if(Window_Call_Keypad==0x03)
				{
					WM_DeleteWindow(hPage[12]);
				  hPage[19]=CreateWindowEnergy_Clear(hPage[18]);
					WM_ShowWindow(hPage[19]);
				}
				else if(Window_Call_Keypad==0x04)
				{
					WM_DeleteWindow(hPage[12]);
					hPage[21]=CreateWindowChange_Password(hPage[18]);
					WM_ShowWindow(hPage[21]);
				}
				else if(Window_Call_Keypad==0x05)
				{
					Acq_MAXClear();
				  WM_DeleteWindow(hPage[12]);
				  hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
					WM_ShowWindow(hPage[8]);
				}
					else if(Window_Call_Keypad==0x06)
				{
					WM_DeleteWindow(hPage[12]);
				  hPage[19]=CreateWindowEnergy_Clear(hPage[8]);
					WM_ShowWindow(hPage[19]);
				}
				else if(Window_Call_Keypad==0x07)
				{
					WM_DeleteWindow(hPage[12]);
					hPage[21]=CreateWindowChange_Password(hPage[8]);
					WM_ShowWindow(hPage[21]);
				}
					else if(Window_Call_Keypad==0x08)
				{
					Alm_RecordClear();
					WM_DeleteWindow(hPage[12]);
				  hPage[11] = CreateWindowHistoryAlarm(WM_HBKWIN);
          WM_ShowWindow(hPage[11]);
				}
					if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
						{
							WM_DeleteWindow(hPage[12]);
							hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
							WM_ShowWindow(hPage[8]);
						}
						else 
						{
							WM_DeleteWindow(hPage[12]);
							hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
							WM_ShowWindow(hPage[18]);
						}
			}
			else if((DropdownSecItemNum==1)&&(PassWord==0))
			{
				User_login=0xCC;
				if(Window_Call_Keypad==0x02)
				{
					Acq_MAXClear();
				  WM_DeleteWindow(hPage[12]);
				  hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
					WM_ShowWindow(hPage[18]);
				}
				else if(Window_Call_Keypad==0x03)
				{
					WM_DeleteWindow(hPage[12]);
				  hPage[19]=CreateWindowEnergy_Clear(hPage[18]);
					WM_ShowWindow(hPage[19]);
				}
				else if(Window_Call_Keypad==0x05)
				{
					Acq_MAXClear();
				  WM_DeleteWindow(hPage[12]);
				  hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
					WM_ShowWindow(hPage[8]);
				}
					else if(Window_Call_Keypad==0x06)
				{
					WM_DeleteWindow(hPage[12]);
				  hPage[19]=CreateWindowEnergy_Clear(hPage[8]);
					WM_ShowWindow(hPage[19]);
				}
				else if(Window_Call_Keypad==0x07)
				{
					WM_DeleteWindow(hPage[12]);
					hPage[21]=CreateWindowChange_Password(hPage[8]);
					WM_ShowWindow(hPage[21]);
				}
				else if(Window_Call_Keypad==0x08)
				{
					Alm_RecordClear();
					WM_DeleteWindow(hPage[12]);
				  hPage[11] = CreateWindowHistoryAlarm(WM_HBKWIN);
          WM_ShowWindow(hPage[11]);
				}
				else if(Window_Call_Keypad==0x01)
				{
					if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
						{
							WM_DeleteWindow(hPage[12]);
							hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
							WM_ShowWindow(hPage[8]);
						}
						else 
						{
							WM_DeleteWindow(hPage[12]);
							hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
							WM_ShowWindow(hPage[18]);
						}
				}
			}
			else 
			{
				PassWord_Error=1;
				WM_InvalidateWindow(pMsg->hWin);
			}
        break;
      }
		}
			if (Id==ID_BUTTON_10) // Notifications sent by 'Cancel'
		{
    switch(NCode) {
       case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
			 	if((Window_Call_Keypad==0x02)||(Window_Call_Keypad==0x03)||(Window_Call_Keypad==0x04))
				{
				  WM_DeleteWindow(hPage[12]);
				  hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
					WM_ShowWindow(hPage[18]);
				}
				else if((Window_Call_Keypad==0x05)||(Window_Call_Keypad==0x06)||(Window_Call_Keypad==0x07))
				{
				  WM_DeleteWindow(hPage[12]);
				  hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
					WM_ShowWindow(hPage[8]);
				}
				else if(Window_Call_Keypad==0x08)
				{
					WM_DeleteWindow(hPage[12]);
				  hPage[11] = CreateWindowHistoryAlarm(WM_HBKWIN);
          WM_ShowWindow(hPage[11]);
				}
				else if(Window_Call_Keypad==0x01)
				{
					if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
						{
							WM_DeleteWindow(hPage[12]);
							hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
							WM_ShowWindow(hPage[8]);
						}
						else 
						{
							WM_DeleteWindow(hPage[12]);
							hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
							WM_ShowWindow(hPage[18]);
						}
				}
				 User_login=0x00;
        break;
      }
		}
      break;
    }		
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}


static void _cbNumberpad(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  unsigned i;
  static int Pressed=0;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem=WM_GetDialogItem(pMsg->hWin, ID_WINDOW_0);
	  WINDOW_SetBkColor(hItem,GUI_LIGHTBLUE);
    
	  for (i = 0; i < 16; i++)
		{
      hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0+i);
			BUTTON_SetFont(hItem, GUI_FONT_16_1);
      BUTTON_SetFocussable(hItem, 0); 	
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		}	
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);      /* Id of widget */
    NCode = pMsg->Data.v;                 /* Notification code */
    switch (NCode) {
    case WM_NOTIFICATION_CLICKED:
      Pressed = 1;
		  break;
    case WM_NOTIFICATION_RELEASED:
      if ((Id >= GUI_ID_USER + 7) && (Id <=GUI_ID_USER + 0x12)) 
			{
        int Key;
        if ((Id >= GUI_ID_USER + 7)&&(Id < GUI_ID_USER + 0x12))  
				{
          char acBuffer[11];
          BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); /* Get the text of the button */
          Key = acBuffer[0];
        } 
				else 
				{
          Key = _aKey[Id - GUI_ID_USER -  0x12];                        /* Get the text from the array */
        }
        GUI_SendKeyMsg(Key, Pressed);                                /* Send a key message to the focussed window */
      }
			if (Id==ID_BUTTON_14)// Notifications sent by 'OK'
			{
			switch(NCode) {
       case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				Keyboard_Call=0;
			  WM_DeleteWindow(hPage[13]);	
        break;
				}
			}
		if (Id==ID_BUTTON_10) // Notifications sent by 'Cancel'
			{
			switch(NCode) {
       case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				 Keyboard_Call=0;
				 WM_DeleteWindow(hPage[13]);	
        break;
				}
			}
      break;
    }	
		break;
  default:
    WM_DefaultProc(pMsg);
	break;
	}
}


static void _cbEnergy(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
    BUTTON_SetText(hItem,"是");
		
		hItem=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
    BUTTON_SetText(hItem,"否");
    break;
	case WM_PAINT:
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0, 0, 110, 75);
	  GUI_SetFont(&GUI_Fontsongti15);
	  GUI_SetColor(GUI_WHITE);
		GUI_SetTextMode(GUI_TM_TRANS);
	  GUI_DispStringAt("是否清除电能?",8,10);
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);      /* Id of widget */
    NCode = pMsg->Data.v;                 /* Notification code */
    switch (NCode) {
    case WM_NOTIFICATION_CLICKED:
		  break;
    case WM_NOTIFICATION_RELEASED:
       switch(Id) {
					case ID_BUTTON_0: // Notifications sent by 'Bus_Data'
						Acq_EnergyClear();	
						gPTE_BaseTime();
						if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
						{
							WM_DeleteWindow(hPage[19]);
              hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
              WM_ShowWindow(hPage[8]);				
            }		
            else 	
            {
							WM_DeleteWindow(hPage[19]);
					    hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
              WM_ShowWindow(hPage[18]);								
            }					
					break;
				case ID_BUTTON_1: // Notifications sent by 'History_Energy'
				    if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
						{
							WM_DeleteWindow(hPage[19]);
              hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
              WM_ShowWindow(hPage[8]);		
            }		
            else 	
            {
							WM_DeleteWindow(hPage[19]);	
					    hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
              WM_ShowWindow(hPage[18]);									
            }	
			    break;
			}
      break;
		 }
		 break;
		default:
			WM_DefaultProc(pMsg);
		break;
	
  }
 }

 
 
 static void _cbChange_Password(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  unsigned i;
	char buf[10];
  static int Pressed=0;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetFont(hItem,&GUI_Fontsongti15);
  	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetFont(hItem,&GUI_Fontsongti15);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem,&GUI_Fontsongti15);
    TEXT_SetText(hItem, "用户名");
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem,&GUI_Fontsongti15);
    TEXT_SetText(hItem, "负责人");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem,&GUI_Fontsongti15);
    TEXT_SetText(hItem, "旧密码");
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem,&GUI_Fontsongti15);
    TEXT_SetText(hItem, "新密码");
	  for (i = 0; i <16; i++)
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0+i);
			BUTTON_SetFont(hItem, GUI_FONT_16_1);
			BUTTON_SetFocussable(hItem, 0); 	
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		}
			hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);  /* Get the handle of the edit widget */
			EDIT_SetText(hItem, "");                   /* Set text */
			EDIT_SetFocussable(hItem,1);
	  	hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_1);  /* Get the handle of the edit widget */
			EDIT_SetText(hItem, "");                   /* Set text */
			EDIT_SetFocussable(hItem,1);
    break;
	case WM_PAINT:
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,0,295,19);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		GUI_DispStringAt("修改密码",5,4);

			break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);      /* Id of widget */
    NCode = pMsg->Data.v;                 /* Notification code */
    switch (NCode) {
    case WM_NOTIFICATION_CLICKED:
      Pressed = 1;
		  break;
    case WM_NOTIFICATION_RELEASED:
      if ((Id >= GUI_ID_USER + 7) && (Id <=GUI_ID_USER + 0x12)) 
			{
        int Key;
        if ((Id >= GUI_ID_USER + 7)&&(Id < GUI_ID_USER + 0x12))  
				{
          char acBuffer[11];
          BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer)); /* Get the text of the button */
          Key = acBuffer[0];
        } 
				else 
				{
          Key = _aKey[Id - GUI_ID_USER -  0x12];                        /* Get the text from the array */
        }
        GUI_SendKeyMsg(Key, Pressed);                                /* Send a key message to the focussed window */
      }
		if(Id==ID_EDIT_0)
		{
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				 WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));	
				break;
			}
		}	
   if(Id==ID_EDIT_1)
		{
		switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				 WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));	
        break;
      }
		}				
				
		if (Id==ID_BUTTON_14)// Notifications sent by 'OK'
		{
		switch(NCode) {
		 case WM_NOTIFICATION_CLICKED:
			break;
		 case WM_NOTIFICATION_RELEASED:
			  EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1), buf, sizeof(buf));
			  UsrPassword= atoi(buf);
        Opt_PWSave();		
		 	  if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
					{
						WM_DeleteWindow(hPage[21]);
						hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
						WM_ShowWindow(hPage[8]);						
					}		
					else 	
					{
						WM_DeleteWindow(hPage[21]);
						hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
						WM_ShowWindow(hPage[18]);								
					}					
			 break;
			}
		}
		if (Id==ID_BUTTON_10) // Notifications sent by 'Cancel'
			{
			switch(NCode) {
       case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				 if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
					{
						WM_DeleteWindow(hPage[21]);
						hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
						WM_ShowWindow(hPage[8]);						
					}		
					else 	
					{
						WM_DeleteWindow(hPage[21]);
						hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
						WM_ShowWindow(hPage[18]);							
					}	
        break;
				}
			}
      break;
    }	
		break;
  default:
    WM_DefaultProc(pMsg);
	break;
	}
}

static void _cbUserlogin_Clear(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
    BUTTON_SetText(hItem,"是");
		
		hItem=WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
    BUTTON_SetText(hItem,"否");
    break;
	case WM_PAINT:
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0, 0, 110, 75);
	  GUI_SetFont(&GUI_Fontsongti15);
	  GUI_SetColor(GUI_WHITE);
		GUI_SetTextMode(GUI_TM_TRANS);
	  GUI_DispStringAt("是否退出登录?",8,10);
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);      /* Id of widget */
    NCode = pMsg->Data.v;                 /* Notification code */
    switch (NCode) {
    case WM_NOTIFICATION_CLICKED:
		  break;
    case WM_NOTIFICATION_RELEASED:
       switch(Id) {
					case ID_BUTTON_0: // Notifications sent by 'YES'
					if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
					{
					  WM_DeleteWindow(hPage[20]);
						WM_DeleteWindow(hPage[8]);
					}
					else
					{
						WM_DeleteWindow(hPage[20]);
					  WM_DeleteWindow(hPage[18]);
					}
				  	User_login = 0; 
					  hPage[0]=CreateWindowHome(WM_HBKWIN);	
            WM_ShowWindow(hPage[0]);	
						
					break;
				case ID_BUTTON_1: // Notifications sent by 'NO'
					  if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
						{
							WM_DeleteWindow(hPage[20]);
							WM_DeleteWindow(hPage[8]);
						}
						else
						{
							WM_DeleteWindow(hPage[20]);
							WM_DeleteWindow(hPage[18]);
						}
				     hPage[0]=CreateWindowHome(WM_HBKWIN);
             WM_ShowWindow(hPage[0]);				
			    break;
			}
      break;
		 }
		 break;
		default:
			WM_DefaultProc(pMsg);
		break;
	
  }
 }

 
 


WM_HWIN CreateWindowKeypad(WM_HWIN hParent);
WM_HWIN CreateWindowKeypad(WM_HWIN hParent) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_KeypadUserCreate, GUI_COUNTOF(_KeypadUserCreate), _cbKeypad, WM_HBKWIN, 0, 0);
  return hWin;
}

WM_HWIN CreateWindowNumberpad(WM_HWIN hParent);
WM_HWIN CreateWindowNumberpad(WM_HWIN hParent) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_NumberpadCreate, GUI_COUNTOF(_NumberpadCreate), _cbNumberpad, WM_HBKWIN, 0, 0);
  return hWin;
}

WM_HWIN CreateWindowEnergy_Clear(WM_HWIN hParent);
WM_HWIN CreateWindowEnergy_Clear(WM_HWIN hParent) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_Energy_ClearCreate, GUI_COUNTOF(_Energy_ClearCreate), _cbEnergy, WM_HBKWIN, 0, 0);
  return hWin;
}

WM_HWIN CreateWindowChange_Password(WM_HWIN hParent);
WM_HWIN CreateWindowChange_Password(WM_HWIN hParent) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_Change_Password, GUI_COUNTOF(_Change_Password), _cbChange_Password, WM_HBKWIN, 0, 0);
  return hWin;
}

WM_HWIN  CreateWindowUserlogin_Clear(WM_HWIN hParent);
WM_HWIN  CreateWindowUserlogin_Clear(WM_HWIN hParent) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_Userlogin_Clear, GUI_COUNTOF(_Userlogin_Clear), _cbUserlogin_Clear, WM_HBKWIN, 0, 0);
  return hWin;
}


// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
