/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "bsp_RTC.h"
#include "bsp_GPIO.h"
#include "app_Optimset.h"
#include "app_SUBProto.h"
#include "string.h"
#include "sys_Variable.h"
#include "stdlib.h"
#include "include.h"
#include "touch.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_BUTTON_3    (GUI_ID_USER + 0x05)
#define ID_BUTTON_4    (GUI_ID_USER + 0x06)
#define ID_BUTTON_5    (GUI_ID_USER + 0x07)
#define ID_BUTTON_6    (GUI_ID_USER + 0x08)
#define ID_TEXT_35    (GUI_ID_USER + 0x09)
#define ID_TEXT_36    (GUI_ID_USER + 0x0A)
#define ID_TEXT_37    (GUI_ID_USER + 0x0B)
#define ID_TEXT_38    (GUI_ID_USER + 0x0C)
#define ID_TEXT_39    (GUI_ID_USER + 0x0D)
#define ID_TEXT_40    (GUI_ID_USER + 0x0E)
#define ID_TEXT_41    (GUI_ID_USER + 0x0F)
#define ID_TEXT_42    (GUI_ID_USER + 0x10)
#define ID_TEXT_0    (GUI_ID_USER + 0x11)
#define ID_TEXT_1    (GUI_ID_USER + 0x12)
#define ID_TEXT_2    (GUI_ID_USER + 0x13)
#define ID_TEXT_3    (GUI_ID_USER + 0x14)
#define ID_TEXT_4    (GUI_ID_USER + 0x15)
#define ID_TEXT_5    (GUI_ID_USER + 0x16)
#define ID_TEXT_6    (GUI_ID_USER + 0x17)
#define ID_TEXT_7    (GUI_ID_USER + 0x18)
#define ID_TEXT_8    (GUI_ID_USER + 0x19)
#define ID_TEXT_9    (GUI_ID_USER + 0x1A)
#define ID_TEXT_10    (GUI_ID_USER + 0x1B)
#define ID_TEXT_11    (GUI_ID_USER + 0x1C)
#define ID_TEXT_12    (GUI_ID_USER + 0x1D)
#define ID_TEXT_13    (GUI_ID_USER + 0x1E)
#define ID_TEXT_14    (GUI_ID_USER + 0x1F)
#define ID_TEXT_15    (GUI_ID_USER + 0x20)
#define ID_TEXT_16    (GUI_ID_USER + 0x21)
#define ID_TEXT_17    (GUI_ID_USER + 0x22)
#define ID_TEXT_18    (GUI_ID_USER + 0x23)
#define ID_TEXT_19    (GUI_ID_USER + 0x24)
#define ID_TEXT_20    (GUI_ID_USER + 0x25)
#define ID_TEXT_43    (GUI_ID_USER + 0x26)
#define ID_TEXT_44    (GUI_ID_USER + 0x27)
#define ID_TEXT_45    (GUI_ID_USER + 0x28)
#define ID_TEXT_46    (GUI_ID_USER + 0x29)
#define ID_TEXT_47    (GUI_ID_USER + 0x2A)
#define ID_TEXT_48    (GUI_ID_USER + 0x2B)
#define ID_TEXT_49    (GUI_ID_USER + 0x2C)
#define ID_TEXT_50    (GUI_ID_USER + 0x2D)
#define ID_TEXT_21    (GUI_ID_USER + 0x2E)
#define ID_TEXT_22    (GUI_ID_USER + 0x2F)
#define ID_TEXT_23    (GUI_ID_USER + 0x30)
#define ID_TEXT_24    (GUI_ID_USER + 0x31)
#define ID_TEXT_25    (GUI_ID_USER + 0x32)
#define ID_TEXT_26    (GUI_ID_USER + 0x33)
#define ID_TEXT_27    (GUI_ID_USER + 0x34)
#define ID_TEXT_28    (GUI_ID_USER + 0x35)
#define ID_TEXT_29    (GUI_ID_USER + 0x36)
#define ID_TEXT_30    (GUI_ID_USER + 0x37)
#define ID_TEXT_31    (GUI_ID_USER + 0x38)
#define ID_TEXT_32    (GUI_ID_USER + 0x3B)
#define ID_TEXT_33    (GUI_ID_USER + 0x3C)
#define ID_TEXT_34    (GUI_ID_USER + 0x3D)

#pragma pack(4)    
typedef struct 
{	
  int32_t touch_x;
  int32_t touch_y;
}Home;
Home Home_Y[144];

union un1   Y;

static const GUI_POINT AHPoints[] = {
{ 204, 118},
{ 208, 127},
{ 212, 118}
};

static const GUI_POINT APoints[] = {
{ 219, 113},
{ 223, 122},
{ 227, 113}
};

static const GUI_POINT BPoints[] = {
{ 243, 113},
{ 247, 122},
{ 251, 113}
};
static const GUI_POINT BranchPoints[] = {
{ 3, 213},
{ 14, 213},
{ 8, 223}
};	

static GUI_RECT Arect = {218, 37, 237, 70};
static GUI_RECT Brect = {239, 37, 252, 70};
static GUI_RECT AHrect = {146, 22, 159, 45};
static GUI_RECT BHrect = {219, 22, 232, 45};
static GUI_RECT ADrect = {218, 27, 237, 60};
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
extern WM_HWIN hPage[25];
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti13;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti15;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti17;
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Bus_Data", ID_BUTTON_0, 1, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Branch_Data", ID_BUTTON_1, 69, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Alarm_information", ID_BUTTON_2, 137, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Last_Page", ID_BUTTON_3, 205, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next_Page", ID_BUTTON_4, 273, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Cut_Bell", ID_BUTTON_5, 341, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "System_Conf", ID_BUTTON_6, 409, 236, 67, 23, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_35, 25, 28, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_36, 25, 52, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_37, 25, 76, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_38, 118, 28, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_39, 118, 52, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_40, 118, 76, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_41, 25, 100, 153, 16, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_42, 25, 124, 153, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_0, 6, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 6, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_2, 6, 76, 18, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_3, 9, 100, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_4, 6, 124, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_5, 86, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_6, 86, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_7, 86, 76, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_8, 99, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_9, 99, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_10, 99, 76, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_11, 180, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_12, 180, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_13, 180, 76, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_14, 179, 100, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_15, 177, 124, 26, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_16, 456, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_17, 456, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_18, 456, 76, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_19, 453, 100, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_20, 450, 124, 26, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_43, 295, 124, 154, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_44, 295, 100, 154, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_45, 389,76, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_46, 295, 76, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_47, 295, 52, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_48, 389, 52, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_49, 389, 28, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_50, 295, 28, 60, 18, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_21, 370, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_22, 370, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_23, 370, 76, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_24, 357, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_25, 357, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_26, 357, 76, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_27, 276, 28, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_28, 276, 52, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_29, 276, 76, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_30, 279, 100, 18, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_31, 276, 124, 20, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_32, 428,259, 45, 13, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_33, 225, 259, 53, 15, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_34, 360, 259, 55, 13, 0, 0x64, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

static void Draw_BusAH_Con(void)
{
  GUI_SetColor(GUI_GREEN);
  GUI_FillRect(126,42,142,76);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(134,49,134,69);
}

static void Draw_BusAH_DisCon(void)
{
  GUI_SetColor(GUI_RED);
  GUI_FillRect(126,42,142,76);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(128,49,134,69);
}

static void Draw_BusBH_Con(void)
{
  GUI_SetColor(GUI_GREEN);
  GUI_FillRect(234,42,250,76);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(242,49,242,69);
}

static void Draw_BusBH_DisCon(void)
{
  GUI_SetColor(GUI_RED);
  GUI_FillRect(234,42,250,76);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(235,49,242,69);
}

static void Draw_H_Mode(void)
{
	int x=150;
	for(int i=0;i<11;i++)
	{
		GUI_DrawLine(x,70,x+5,70);
		x+=7;
	}
	GUI_DrawLine(188,71,180,80);
	GUI_DrawLine(188,71,196,80);
	GUI_DrawLine(180,80,196,80);
}

static void Draw_BusA_DisCon(void)
{
  GUI_SetColor(GUI_RED);
  GUI_FillRect(200,57,216,91);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(202,64,208,84);
}

static void Draw_BusA_Con(void)
{
  GUI_SetColor(GUI_GREEN);
  GUI_FillRect(200,57,216,91);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(208,64,208,84);
}


static void Draw_BusB_Con(void)
{
  GUI_SetColor(GUI_GREEN);
  GUI_FillRect(254,57,270,91);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(262,64,262,84);
}

static void Draw_BusB_DisCon(void)
{
  GUI_SetColor(GUI_RED);
  GUI_FillRect(254,57,270,91);
  GUI_SetColor(GUI_BLUE);
  GUI_DrawLine(256,64,262,84);
}
int Branch_Num=0;

static void Branch_Con(int i)
{
  GUI_SetColor(GUI_GREEN);
	GUI_FillRect(20*i+2,175,20*i+15,205);
	GUI_SetColor(GUI_BLUE);
	GUI_DrawLine(20*i+8,180,20*i+8,200);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(20*i+8,180,2);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(20*i+8,200,2);
	GUI_SetColor(GUI_BLUE);
	GUI_DrawLine(20*i+8,175,20*i+8,180);
	GUI_DrawLine(20*i+8,200,20*i+8,205);
}
static void Branch_DisCon(int i)
{
	GUI_SetColor(GUI_RED);
	GUI_FillRect(20*i+2,175,20*i+15,205);
	GUI_SetColor(GUI_BLUE);
	GUI_DrawLine(20*i+3,183,20*i+8,200);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(20*i+8,180,2);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(20*i+8,200,2);
	GUI_SetColor(GUI_BLUE);
	GUI_DrawLine(20*i+8,175,20*i+8,180);
	GUI_DrawLine(20*i+8,200,20*i+8,205);
}

static void Branch_DisConB(int i)
{
	GUI_SetColor(GUI_RED);
	GUI_FillRect(239+20*i+2,175,239+20*i+15,205);
	GUI_SetColor(GUI_BLUE);
	GUI_DrawLine(239+20*i+3,183,239+20*i+8,200);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(239+20*i+8,180,2);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(239+20*i+8,200,2);
	GUI_SetColor(GUI_BLUE);
	GUI_DrawLine(239+20*i+8,175,239+20*i+8,180);
	GUI_DrawLine(239+20*i+8,200,239+20*i+8,205);
}
static void Branch_ConB(int i)
{
	GUI_SetColor(GUI_GREEN);
	GUI_FillRect(239+20*i+2,175,239+20*i+15,205);
	GUI_SetColor(GUI_BLUE);
	GUI_DrawLine(239+20*i+8,180,239+20*i+8,200);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(239+20*i+8,180,2);
	GUI_SetColor(GUI_BLUE);
	GUI_FillCircle(239+20*i+8,200,2);
	GUI_DrawLine(239+20*i+8,175,239+20*i+8,180);
	GUI_DrawLine(239+20*i+8,200,239+20*i+8,205);
}

static void Branchnum_DisplayS_B(int i,int Page)
{
	 if(Page==0x00)
		 {
			if(i<9) 
				GUI_DispDecAt(i+1,239+20*i+9,160,1);
			else GUI_DispDecAt(i+1,239+20*i+9,160,2);
		 }
	 if(Page==0x01)
		 GUI_DispDecAt(i+13,239+20*i+9,160,2);
	 if(Page==0x02)
		 GUI_DispDecAt(i+25,239+20*i+9,160,2);
	 if(Page==0x03)
		 GUI_DispDecAt(i+37,239+20*i+9,160,2);
	 if(Page==0x04)
		 GUI_DispDecAt(i+49,239+20*i+9,160,2);
	 if(Page==0x05)
		 GUI_DispDecAt(i+61,239+20*i+9,160,2);
}

static void Branchnum_DisplayS_A(int i,int Page)
{
	 if(Page==0x00)
		 {
			if(i<9) 
				GUI_DispDecAt(i+1,20*i+9,160,1);
			else GUI_DispDecAt(i+1,20*i+9,160,2);
		 }
	 if(Page==0x01)
		 GUI_DispDecAt(i+13,20*i+9,160,2);
	 if(Page==0x02)
		 GUI_DispDecAt(i+25,20*i+9,160,2);
	 if(Page==0x03)
		 GUI_DispDecAt(i+37,20*i+9,160,2);
	 if(Page==0x04)
		 GUI_DispDecAt(i+49,20*i+9,160,2);
	 if(Page==0x05)
		 GUI_DispDecAt(i+61,20*i+9,160,2);
}


static void Branchnum_Display(int i,int Page)
{
	 if(Page==0x00)
	 {
		if(i<9) 
			GUI_DispDecAt(i+1,20*i+9,160,1);
		else  GUI_DispDecAt(i+1,20*i+9,160,2);
	 }
	 if(Page==0x01)
		 GUI_DispDecAt(i+25,20*i+9,160,2);
	 if(Page==0x02)
		 GUI_DispDecAt(i+49,20*i+9,160,2);
	 if(Page==0x03)
		 GUI_DispDecAt(i+73,20*i+9,160,2);
	 if(Page==0x04)
	 {
		 if(i<3)
			GUI_DispDecAt(i+97,20*i+9,160,2);
		 else GUI_DispDecAt(i+97,20*i+3,160,3);
	 }
	 if(Page==0x05)
		 GUI_DispDecAt(i+121,20*i+3,160,3);
}

static int Draw_Branch_Switch(int Page)
{ 
  int MaxPage=0;
	Branch_Num=Optimset_st.ucBranchN_a[0];
	if(Branch_Num/24>=1)
	{
		if(Branch_Num%24==0)
		{
			MaxPage=Branch_Num/24;
			for(int i=0;i<24;i++)
			{
			 Branch_Con(i); 
			 GUI_SetColor(GUI_BLUE);
			 GUI_DrawLine(20*i+8,200,20*i+8,213);
			 GUI_SetColor(GUI_BLUE);
			 GUI_DrawLine(20*i+8,150,20*i+8,180);
			 GUI_SetColor(GUI_BLUE);
			 Home_Y[Page*24+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
			 Home_Y[Page*24+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
			 if (GUI_TOUCH_X_MeasureX()!=0)	
		   {
			 	if((abs(Home_Y[Page*24+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*24+i].touch_y-adc_y)<300))
				{
						if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*24+i] = !ucBranchSet_a[Page*24+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*24+i],Page*24+i);
						}
				 }
			  }
				SUB_BranchState();
				if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*24+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
			
			}
		}
		else 
		{
			MaxPage=Branch_Num/24+1;
			if(Page<MaxPage-1)
			{
				for(int i=0;i<24;i++)
				{
					Branch_Con(i); 
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(20*i+8,200,20*i+8,213);
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(20*i+8,150,20*i+8,180);
					GUI_SetColor(GUI_BLUE);
			    Home_Y[Page*24+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
			    Home_Y[Page*24+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
			   	 if (GUI_TOUCH_X_MeasureX()!=0)	
		   {
			 	if((abs(Home_Y[Page*24+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*24+i].touch_y-adc_y)<300))
				{
						if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*24+i] = !ucBranchSet_a[Page*24+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*24+i],Page*24+i);
						}
				 }
			  }
				SUB_BranchState();
				if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*24+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
			}
		}
			else 
			{
				for(int i=0;i<Branch_Num%24;i++)
				{
					Branch_Con(i); 
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(20*i+8,200,20*i+8,213);
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(20*i+8,150,20*i+8,180);
					GUI_SetColor(GUI_BLUE);
			    Home_Y[Page*24+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
			    Home_Y[Page*24+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
			  	 if (GUI_TOUCH_X_MeasureX()!=0)	
		   {
			 	if((abs(Home_Y[Page*24+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*24+i].touch_y-adc_y)<300))
				{
						if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*24+i] = !ucBranchSet_a[Page*24+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*24+i],Page*24+i);
						}
				 }
			  }
				SUB_BranchState();
		  if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*24+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
			  }
		  }
	  }
  }
	else
	{
		MaxPage=1;
		for(int i=0;i<Branch_Num;i++)
		{
		 Branch_Con(i); 
		 GUI_SetColor(GUI_BLUE);
		 GUI_DrawLine(20*i+8,200,20*i+8,213);
		 GUI_SetColor(GUI_BLUE);
		 GUI_DrawLine(20*i+8,150,20*i+8,180);
		 GUI_SetColor(GUI_BLUE);
		 Home_Y[Page*24+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
		 Home_Y[Page*24+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
			 if (GUI_TOUCH_X_MeasureX()!=0)	
		   {
			 	if((abs(Home_Y[Page*24+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*24+i].touch_y-adc_y)<300))
				{
						if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*24+i] = !ucBranchSet_a[Page*24+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*24+i],Page*24+i);
						}
				 }
			  }
				SUB_BranchState();
		   if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*24+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_Display(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
		}
	}
	return MaxPage;
}

int Branch_NumA=0,Branch_NumB=0;
static int Draw_Branch_SwitchA(int Page)
{
	static int MaxPageA=0;
	Branch_NumA=Optimset_st.ucBranchN_a[0];
	if(Branch_NumA/12>=1)
	{
		if(Branch_NumA%12==0)
		{
			MaxPageA=Branch_NumA/12;
			for(int i=0;i<12;i++)
			{
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(20*i+8,200,20*i+8,213);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(20*i+8,150,20*i+8,180);
				GUI_SetColor(GUI_BLUE);
				Home_Y[Page*12+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
				Home_Y[Page*12+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
			 	if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
					if((abs(Home_Y[Page*12+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+i].touch_y-adc_y)<300))
					{
								if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*12+i] = !ucBranchSet_a[Page*12+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*12+i],Page*12+i);
						}
					}
				}
				SUB_BranchState();
		    if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
			}
		}
			else 
		{
			MaxPageA=Branch_NumA/12+1;
			if(Page<MaxPageA-1)
			{
				for(int i=0;i<12;i++)
				{
				  Branch_Con(i); 
				  GUI_SetColor(GUI_BLUE);
				  GUI_DrawLine(20*i+8,200,20*i+8,213);
				  GUI_SetColor(GUI_BLUE);
				  GUI_DrawLine(20*i+8,150,20*i+8,180);
				  GUI_SetColor(GUI_BLUE);
				  Home_Y[Page*12+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
					Home_Y[Page*12+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
					 	if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
					if((abs(Home_Y[Page*12+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+i].touch_y-adc_y)<300))
					{
								if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*12+i] = !ucBranchSet_a[Page*12+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*12+i],Page*12+i);
						}
					}
				}
					SUB_BranchState();
		    if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
				}
			}
			else if(Page==MaxPageA-1)
			{
				for(int i=0;i<Branch_NumA%12;i++)
				{ 
				  GUI_SetColor(GUI_BLUE);
				  GUI_DrawLine(20*i+8,200,20*i+8,213);
				  GUI_SetColor(GUI_BLUE);
				  GUI_DrawLine(20*i+8,150,20*i+8,180);
				  GUI_SetColor(GUI_BLUE);
				  Home_Y[Page*12+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
					Home_Y[Page*12+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
			 	if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
					if((abs(Home_Y[Page*12+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+i].touch_y-adc_y)<300))
					{
								if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*12+i] = !ucBranchSet_a[Page*12+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*12+i],Page*12+i);
						}
					}
				}
					SUB_BranchState();
        if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
				}
			}
		}
	}
	else 
	{
		MaxPageA=1;
		for(int i=0;i<Branch_NumA;i++)
		{
			GUI_SetColor(GUI_BLUE);
			GUI_DrawLine(20*i+8,200,20*i+8,213);
			GUI_SetColor(GUI_BLUE);
			GUI_DrawLine(20*i+8,150,20*i+8,180);
			GUI_SetColor(GUI_BLUE);
			Home_Y[Page*12+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(8+20*i-20);
			Home_Y[Page*12+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
			 	if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
					if((abs(Home_Y[Page*12+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+i].touch_y-adc_y)<300))
					{
								if((User_login==0xFF)||(User_login==0xCC))
						{
							 ucBranchSet_a[Page*12+i] = !ucBranchSet_a[Page*12+i];
							 Opt_BranchSet_Save(ucBranchSet_a[Page*12+i],Page*12+i);
						}
					}
				}
			SUB_BranchState();
		   if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_Con(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisCon(i);
									GUI_FillPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_Con(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisCon(i);
									GUI_DrawPolygon(BranchPoints,3,20*i,0);
									Branchnum_DisplayS_A(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,20*i,0);
    }
  }
	return MaxPageA;
}

static int Draw_Branch_SwitchB(int Page)
{
	static int  k=239,MaxPageB=0;
	Branch_NumB=Optimset_st.ucBranchN_a[1];
	if(Branch_NumB/12>=1)
	{
		if(Branch_NumB%12==0)
		{
			MaxPageB=Branch_NumB/12;
			for(int i=0;i<12;i++)
			{ 
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(k+20*i+8,200,k+20*i+8,213);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(k+20*i+8,150,k+20*i+8,180);
				GUI_SetColor(GUI_BLUE);
				Home_Y[Page*12+72+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(k+8+20*i-20);
				Home_Y[Page*12+72+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
				if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
			 	if((abs(Home_Y[Page*12+72+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+72+i].touch_y-adc_y)<300))
					{
							if((User_login==0xFF)||(User_login==0xCC))
						{
					   ucBranchSet_a[Page*12+72+i] = !ucBranchSet_a[Page*12+72+i];
						 Opt_BranchSet_Save(ucBranchSet_a[Page*12+72+i],Page*12+72+i);
				 	}
				 }
				}
				SUB_BranchState();
				if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+72+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_ConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_ConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
			
			}
		}
			else 
		{
			MaxPageB=Branch_NumB/12+1;
			if(Page<MaxPageB-1)
			{
				for(int i=0;i<12;i++)
				{
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(k+20*i+8,200,k+20*i+8,213);
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(k+20*i+8,150,k+20*i+8,180);
					GUI_SetColor(GUI_BLUE);
					Home_Y[Page*12+72+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(k+8+20*i-20);
				Home_Y[Page*12+72+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
							if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
			 	if((abs(Home_Y[Page*12+72+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+72+i].touch_y-adc_y)<300))
					{
							if((User_login==0xFF)||(User_login==0xCC))
						{
					   ucBranchSet_a[Page*12+72+i] = !ucBranchSet_a[Page*12+72+i];
						 Opt_BranchSet_Save(ucBranchSet_a[Page*12+72+i],Page*12+72+i);
				 	}
				 }
				}
				SUB_BranchState();
				if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+72+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_ConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_ConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
				}
			}
			else if(Page==MaxPageB-1)
			{
				for(int i=0;i<Branch_NumB%12;i++)
				{
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(k+20*i+8,200,k+20*i+8,213);
					GUI_SetColor(GUI_BLUE);
					GUI_DrawLine(k+20*i+8,150,k+20*i+8,180);
					GUI_SetColor(GUI_BLUE);
					Home_Y[Page*12+72+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(k+8+20*i-20);
				Home_Y[Page*12+72+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
							if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
			 	if((abs(Home_Y[Page*12+72+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+72+i].touch_y-adc_y)<300))
					{
							if((User_login==0xFF)||(User_login==0xCC))
						{
					   ucBranchSet_a[Page*12+72+i] = !ucBranchSet_a[Page*12+72+i];
						 Opt_BranchSet_Save(ucBranchSet_a[Page*12+72+i],Page*12+72+i);
				 	}
				 }
				}
				SUB_BranchState();
				if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+72+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_ConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_ConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
				}
			}
		}
	}
	else 
	{
		MaxPageB=1;
		for(int i=0;i<Branch_NumB;i++)
		{
			/*B路*/

			GUI_SetColor(GUI_BLUE);
			GUI_DrawLine(k+20*i+8,200,k+20*i+8,213);
			GUI_SetColor(GUI_BLUE);
			GUI_DrawLine(k+20*i+8,150,k+20*i+8,180);
			GUI_SetColor(GUI_BLUE);
			Home_Y[Page*12+72+i].touch_x=(float)cal_value.touch_x[0]+cal_value.kx*(k+8+20*i-20);
				Home_Y[Page*12+72+i].touch_y=(float)cal_value.touch_y[0]+cal_value.ky*(200-20);
				if (GUI_TOUCH_X_MeasureX()!=0)	
		    {
			 	if((abs(Home_Y[Page*12+72+i].touch_x-adc_x)<60)&&(abs(Home_Y[Page*12+72+i].touch_y-adc_y)<300))
					{
							if((User_login==0xFF)||(User_login==0xCC))
						{
					   ucBranchSet_a[Page*12+72+i] = !ucBranchSet_a[Page*12+72+i];
						 Opt_BranchSet_Save(ucBranchSet_a[Page*12+72+i],Page*12+72+i);
				  	}
				  }
				}
				SUB_BranchState();
								if(Optimset_st.Setup.Setup_st.bQF==0x01)
				{
					switch(ucBranchState_a[Page*12+72+i])
					{
						 /* 开关正常 */
						 case 0x00:
									Branch_ConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关故障 */
						 case  0x01:
									Branch_DisConB(i);
									GUI_FillPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关闭合 */
						 case 0x02:
									Branch_ConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 /* 开关断开 */
						 case 0x03:
									Branch_DisConB(i);
									GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
									Branchnum_DisplayS_B(i,Page);
									break;
						 default:break;
					}
				}
				else   GUI_DrawPolygon(BranchPoints,3,k+20*i,0);
    }
  }
	return MaxPageB;
}




/*
*********************************************************************************************************
*	函 数 名: Caculate_RTC
*	功能说明: 显示RTC时间
*	形    参：pMsg 指针参数            
*	返 回 值: 无
*********************************************************************************************************
*/

 void Caculate_RTC(WM_MESSAGE * pMsg,int ID_TEXT_Data,int ID_TEXT_Time)
{
		RTC_TimeTypeDef  RTC_TimeStructure;
		RTC_DateTypeDef  RTC_DateStructure;
	  char buf[30];
	  WM_HWIN hWin = pMsg->hWin;
	  HAL_RTC_GetTime(&hrtc,&RTC_TimeStructure,RTC_FORMAT_BIN);
	  HAL_RTC_GetDate(&hrtc,&RTC_DateStructure,RTC_FORMAT_BIN);
	  sprintf(buf,"%0.2d:%0.2d:%0.2d:", 
			  RTC_TimeStructure.Hours, 
			  RTC_TimeStructure.Minutes,
			  RTC_TimeStructure.Seconds);
	 TEXT_SetText(WM_GetDialogItem(hWin,ID_TEXT_Time), buf);
	 TEXT_SetTextColor(WM_GetDialogItem(hWin,ID_TEXT_Time),GUI_WHITE);
	 sprintf(buf,"20%0.2d/%0.2d/%0.2d", 
			  RTC_DateStructure.Year, 
			  RTC_DateStructure.Month, 
			  RTC_DateStructure.Date);
	 TEXT_SetText(WM_GetDialogItem(hWin,ID_TEXT_Data), buf); 
   TEXT_SetTextColor(WM_GetDialogItem(hWin,ID_TEXT_Data),GUI_WHITE);	
}

void Home_Init(WM_MESSAGE * pMsg,WM_HWIN hItem)
{
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"母线数据");
  	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"历史电能");
  	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"报警信息");
  	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"上一页");
  	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"下一页");
  	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"切铃");
  	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"系统配置");
  	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetText(hItem, "A");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetText(hItem, "A");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetText(hItem, "A");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetText(hItem, "KW");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
    TEXT_SetText(hItem, "KWh");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
    TEXT_SetText(hItem, "Ia");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem, &GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
    TEXT_SetText(hItem, "Ib");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_23);
    TEXT_SetText(hItem, "Ic");
    TEXT_SetTextColor(hItem,GUI_BLUE);
		TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_24);
    TEXT_SetText(hItem, "V");
    TEXT_SetTextColor(hItem,GUI_BLUE);
		TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_25);
    TEXT_SetText(hItem, "V");
    TEXT_SetTextColor(hItem,GUI_BLUE);
		TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_26);
    TEXT_SetText(hItem, "V");
    TEXT_SetTextColor(hItem,GUI_BLUE);
		TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_27);
    TEXT_SetText(hItem, "Ua");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_28);
    TEXT_SetText(hItem, "Ub");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_29);
    TEXT_SetText(hItem, "Uc");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_30);
    TEXT_SetText(hItem, "P");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_31);
    TEXT_SetText(hItem, "EP");
    TEXT_SetTextColor(hItem,GUI_BLUE);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_43);
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
		TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_44);
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
		TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_45);
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
		TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_46);
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
		TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_47);
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);	
    TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_48);
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
		TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_49);	
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);	
    TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_50);
		TEXT_SetTextColor(hItem,GUI_BLACK);
    TEXT_SetFont(hItem,&GUI_Fontsongti17);
		TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
		if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
			TEXT_SetText(hItem, "Ua");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
			TEXT_SetText(hItem, "Ub");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
			TEXT_SetText(hItem, "Uc");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
			TEXT_SetText(hItem, "P");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
			TEXT_SetText(hItem, "EP");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
			TEXT_SetText(hItem, "V");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
			TEXT_SetText(hItem, "V");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
			TEXT_SetText(hItem, "V");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
			TEXT_SetText(hItem, "Ia");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
			TEXT_SetText(hItem, "Ib");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
			TEXT_SetText(hItem, "Ic");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
			TEXT_SetText(hItem, "A");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
			TEXT_SetText(hItem, "A");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
			TEXT_SetText(hItem, "A");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
			TEXT_SetText(hItem, "KW");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
			TEXT_SetText(hItem, "KWh");
			TEXT_SetTextColor(hItem,GUI_BLUE);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_35);
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_36);
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_37);
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_38);
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_39);
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);	
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);		
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_40);
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_41);	
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);	
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);		
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_42);
			TEXT_SetTextColor(hItem,GUI_BLACK);
			TEXT_SetFont(hItem,&GUI_Fontsongti17);
			TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
	}	
}

static void _cbWindow_Home(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	static int Page=0,MaxPage=0,MaxPageA=0,MaxPageB=0;
  char buf[30];
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    Home_Init(pMsg,hItem);
    break;
		
		case WM_PAINT:  
			/******A路*******/
	
			if(X.BusStatus_st_a[0].bQF == 0)
			{
				if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeD))
				  Draw_BusA_Con();
				else
					Draw_BusAH_Con();	 
			}
			else
			{
				if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeD))
				  Draw_BusA_DisCon();
				else
					Draw_BusAH_DisCon();
			}
			if(X.BusStatus_st_a[0].bSPD == 0)
			{
				if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeD))
				{
				  GUI_SetColor(GUI_GREEN);     //A防雷正常
				  GUI_FillPolygon(APoints,3,0,0);
				}
				else 
				{
					GUI_SetColor(GUI_GREEN);     //A防雷正常
				  GUI_FillPolygon(AHPoints,3,0,0);
				}
			}
			else
			{
				if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeD))
				{
				  GUI_SetColor(GUI_RED);     //A防雷故障
				  GUI_FillPolygon(APoints,3,0,0);
				}
				else 
				{
					GUI_SetColor(GUI_RED);     //A防雷故障
				  GUI_FillPolygon(AHPoints,3,0,0);
				}
			}

      if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
			{
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(208,20,208,62);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(208,62,2);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(208,86,2);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(208,86,208,150);

				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(208,97,223,97);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(223,97,223,112);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawRect(217,104,229,128);
				
				GUI_SetColor(GUI_BLUE);      //接地
				GUI_DrawLine(223,128,223,135);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(218,135,228,135);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(220,138,226,138);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(222,141,224,141);
		  }
			else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD)
			{
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(208,20,208,62);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(208,62,2);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(208,86,2);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(208,86,208,150);

				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(208,97,223,97);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(223,97,223,112);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawRect(217,104,229,128);


				GUI_SetColor(GUI_BLUE);      //接地
				GUI_DrawLine(223,128,223,135);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(218,135,228,135);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(220,138,226,138);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(222,141,224,141);
			}
			else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH)
			{
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(134,20,134,47);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(134,47,2);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(134,71,2);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(134,71,134,90);

				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(208,98,208,109);
				GUI_DrawLine(188,98,208,98);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawRect(202,109,214,133);

				GUI_SetColor(GUI_BLUE);      //接地
				GUI_DrawLine(208,133,208,140);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(203,140,213,140);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(205,143,211,143);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(207,146,209,146);
			}

			/******B路*******/
			if(X.BusStatus_st_a[1].bQF == 0x00)
			{
				if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
				  Draw_BusB_Con();
				else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH)
					Draw_BusBH_Con();	 
			}
			else
			{
				if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
			    Draw_BusB_DisCon();
				else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH)
					Draw_BusBH_DisCon();	
			}
			if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
			{
				if(X.BusStatus_st_a[1].bSPD == 0x00)
				{
					GUI_SetColor(GUI_GREEN);     //B防雷正常
					GUI_FillPolygon(BPoints,3,0,0);
				}
				else 
				{
					GUI_SetColor(GUI_RED);       //B防雷故障
					GUI_FillPolygon(BPoints,3,0,0);
				}
		  }
			if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
			{
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(262,20,262,62);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(262,62,2);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(262,86,2);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(262,86,262,150);

				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(262,97,247,97);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(247,97,247,112);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawRect(241,104,253,128);

				GUI_SetColor(GUI_BLUE);      //接地
				GUI_DrawLine(247,128,247,135);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(242,135,252,135);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(244,138,250,138);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(246,141,248,141);
		  }
			else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH)
			{
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(242,20,242,47);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(242,47,2);
				GUI_SetColor(GUI_BLUE);
				GUI_FillCircle(242,71,2);
				GUI_DrawLine(188,90,188,150);
				GUI_SetColor(GUI_BLUE);
				GUI_DrawLine(242,71,242,90);
				GUI_DrawLine(134,90,242,90);
			}

			if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
			{
				GUI_DrawLine(0,150,228,150);
			  GUI_DrawLine(247,150,480,150);
				MaxPageA=Draw_Branch_SwitchA(Page);
		 	  MaxPageB=Draw_Branch_SwitchB(Page);
				if(MaxPageA>=MaxPageB)
					MaxPage=MaxPageA;
				else 	
					MaxPage=MaxPageB;
			}
			else 
			{
				GUI_DrawLine(0,150,480,150);
				MaxPage=Draw_Branch_Switch(Page);
			}
			if(Optimset_st.Setup.Setup_st.bQF==0x01)
			{
				sprintf(buf,"%d / %d",Page+1,MaxPage);
				TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_33),buf);
				TEXT_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_TEXT_33),GUI_WHITE);
			}
			GUI_SetColor(GUI_LIGHTBLUE);
			GUI_FillRect(0,0,480,20);
			GUI_SetColor(GUI_LIGHTBLUE);
	  	GUI_FillRect(0,260,480,272);
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
      GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
			{
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",140,3);
				GUI_SetFont(&GUI_Fontsongti13);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringAt("A",222,22);
				GUI_SetTextMode(GUI_TM_TRANS);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawRectEx(&Arect);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringInRectWrap("母线", &Arect, GUI_TA_LEFT, GUI_WRAPMODE_WORD);

				GUI_SetFont(&GUI_Fontsongti13);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringAt("B",243,22);

				GUI_SetTextMode(GUI_TM_TRANS);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawRectEx(&Brect);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringInRectWrap("母线", &Brect, GUI_TA_LEFT, GUI_WRAPMODE_WORD);
			}
			else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD)
			{
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",140,3);
				GUI_SetFont(&GUI_Fontsongti13);
				GUI_SetTextMode(GUI_TM_TRANS);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawRectEx(&ADrect);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringInRectWrap("母线", &ADrect, GUI_TA_LEFT, GUI_WRAPMODE_WORD);
			}
			else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH)
			{
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",140,3);
				GUI_SetFont(&GUI_Fontsongti13);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringAt("A",150,48);
				GUI_SetTextMode(GUI_TM_TRANS);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawRectEx(&AHrect);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringInRectWrap("母线", &AHrect, GUI_TA_LEFT, GUI_WRAPMODE_WORD);

				GUI_SetFont(&GUI_Fontsongti13);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringAt("B",223,48);

				GUI_SetTextMode(GUI_TM_TRANS);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawRectEx(&BHrect);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringInRectWrap("母线", &BHrect, GUI_TA_LEFT, GUI_WRAPMODE_WORD);
				Draw_H_Mode();
			}
			else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeY)
			{
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",140,3);
				GUI_SetFont(&GUI_Fontsongti13);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringAt("A",222,22);
				GUI_SetTextMode(GUI_TM_TRANS);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawRectEx(&Arect);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringInRectWrap("母线", &Arect, GUI_TA_LEFT, GUI_WRAPMODE_WORD);

				GUI_SetFont(&GUI_Fontsongti13);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringAt("B",243,22);

				GUI_SetTextMode(GUI_TM_TRANS);
				GUI_SetColor(GUI_WHITE);
				GUI_DrawRectEx(&Brect);
				GUI_SetColor(GUI_BLUE);
				GUI_DispStringInRectWrap("母线", &Brect, GUI_TA_LEFT, GUI_WRAPMODE_WORD);
			}
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Font13_1);
      GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		  GUI_DispStringAt(SoftVersion,5,4);
			
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
      GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		  GUI_DispStringAt("主页",430,3);
	break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	  switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:			

						switch(Id) {
							case ID_BUTTON_0: // Notifications sent by 'Bus_Data'
								   Page=0;
							   	 WM_DeleteWindow(hPage[0]);
									 hPage[4] = CreateWindowBusData_1(WM_HBKWIN);
									 WM_ShowWindow(hPage[4]);
							break;
						case ID_BUTTON_1: // Notifications sent by 'History_Energy'
							     Page=0;
						     	 WM_DeleteWindow(hPage[0]);
									 hPage[14] = CreateWindowAHistory_Energy_1(WM_HBKWIN);
									 WM_ShowWindow(hPage[14]);
							break;
						case ID_BUTTON_2: // Notifications sent by 'Alarm_information'
							     Page=0;
							     WM_DeleteWindow(hPage[0]);
									 hPage[10] = CreateWindowNowAlarm(WM_HBKWIN);
									 WM_ShowWindow(hPage[10]);
							break;
						case ID_BUTTON_3: // Notifications sent by 'Last_Page'
									 if(Page>0)
									 if(Optimset_st.Setup.Setup_st.bQF==0x01)
									 {
										 Page--;
									   WM_InvalidateWindow(pMsg->hWin);
									 }
							break;
						case ID_BUTTON_4: // Notifications sent by 'Next_Page'
									 if(Page<MaxPage-1)
									 if(Optimset_st.Setup.Setup_st.bQF==0x01)
									 {
										 Page++;
									   WM_InvalidateWindow(pMsg->hWin);
									 }
							break;
						case ID_BUTTON_5: // Notifications sent by 'Cut_Bell'
						     ALM_AURAL_Toggle();
							break;
						case ID_BUTTON_6: // Notifications sent by 'System_Conf'
							  Page=0;
								if(User_login==0)
								{
									 Window_Call_Keypad=0x01;
									 hPage[12] = CreateWindowKeypad(hPage[0]);
									 WM_ShowWindow(hPage[12]);
								}
								else
								{
									WM_DeleteWindow(hPage[0]);
									if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
									{
									  hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
										WM_ShowWindow(hPage[8]);
									}
									else
									{
										hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
										WM_ShowWindow(hPage[18]);
									}
								}
								break;	   						 
							}
							break;
						}
				break;
		case WM_TIMER://定时器消息,到时间时有效 
				Caculate_RTC(pMsg,ID_TEXT_34,ID_TEXT_32);
		    if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
		    {
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUa);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_35),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUb);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_36),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUc);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_37),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIa);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_38),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIb);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_39),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIc);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_40),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPt);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_41),buf);
					sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[0].uiEPt)/100));
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_42),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUa);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_50),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUb);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_47),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUc);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_46),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fIa);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_49),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fIb);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_48),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fIc);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_45),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPt);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_44),buf);
					sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[1].uiEPt)/100));
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_43),buf);
			  }
				else 
				{
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUa);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_50),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUb);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_47),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUc);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_46),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIa);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_49),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIb);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_48),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIc);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_45),buf);
					sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPt);
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_44),buf);
					sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[0].uiEPt)/100));
					TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_43),buf);
				}
			
					if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeH))
					{
						if((Y.ucBusStatus[0]!=X.ucBusStatus[0]) || (Y.ucBusStatus[1]!=X.ucBusStatus[1]))
						{
							 WM_InvalidateWindow(pMsg->hWin);
							 Y.ucBusStatus[0]=X.ucBusStatus[0];
							 Y.ucBusStatus[1]=X.ucBusStatus[1];
						}
					}
					else
					{
						if(Y.ucBusStatus[0]!=X.ucBusStatus[0])
						{
							 WM_InvalidateWindow(pMsg->hWin);
							 Y.ucBusStatus[0]=X.ucBusStatus[0];
						}
					}
				if ((GUI_TOUCH_X_MeasureX()!=0) || (IOChangeFlag != 0))
					{
						IOChangeFlag = 0;
						WM_InvalidateWindow(pMsg->hWin);
					}
				WM_RestartTimer(pMsg->Data.v,100);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateWindowHome(WM_HWIN hParent);
WM_HWIN CreateWindowHome(WM_HWIN hParent)
{ 
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbWindow_Home, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,200,0);
	
	return hWin;
}




// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
