/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include.h"
#include "sys_Variable.h"
#include "app_Optimset.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x01)
#define ID_LISTVIEW_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_0    (GUI_ID_USER + 0x03)
#define ID_BUTTON_1    (GUI_ID_USER + 0x04)
#define ID_BUTTON_2    (GUI_ID_USER + 0x05)
#define ID_BUTTON_3    (GUI_ID_USER + 0x06)
#define ID_BUTTON_4    (GUI_ID_USER + 0x07)
#define ID_TEXT_0      (GUI_ID_USER + 0x08)
#define ID_TEXT_1      (GUI_ID_USER + 0x09)


static const GUI_WIDGET_CREATE_INFO _BusData_1[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 20, 480, 212, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next_Page", ID_BUTTON_0, 273, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 137, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 205, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_3, 342, 236, 68, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Help", ID_BUTTON_4, 411, 236, 67, 23, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_0, 428,259, 45, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 360, 259, 55, 15, 0, 0x64, 0 },
};

static const GUI_WIDGET_CREATE_INFO _BusData_2[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 20, 480, 212, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Last_Page", ID_BUTTON_0, 273, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 137, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 205, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_3, 342, 236, 68, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Help", ID_BUTTON_4, 411, 236, 67, 23, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_0, 428,259, 45, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_1, 360, 259, 55, 15, 0, 0x64, 0 },
};

extern WM_HWIN hPage[25];
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti15;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti17;


static uint8_t B_BusData=0;
static uint8_t B_BusData2=0;

static void _cbWindow_BusData_1(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  char buf[30];
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
	  LISTVIEW_SetHeaderHeight(hItem, 22);
	  HEADER_SetTextColor(LISTVIEW_GetHeader(hItem),GUI_BLUE_98);
    HEADER_SetFont(LISTVIEW_GetHeader(hItem),&GUI_Fontsongti17);
    LISTVIEW_AddColumn(hItem, 80, "项目", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "A相/AB", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "B相/BC", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_AddColumn(hItem, 80, "C相/CA", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "合相", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_AddColumn(hItem, 80, "单位", GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetRowHeight(hItem,19);
		LISTVIEW_SetFont(hItem,&GUI_Fontsongti15);
	  LISTVIEW_SetItemText(hItem,0,0,"相电压");
		LISTVIEW_SetItemTextColor(hItem,0,0,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,0,"--");
		LISTVIEW_SetItemText(hItem,5,0,"V");
		LISTVIEW_SetItemTextColor(hItem,5,0,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,1,"线电压");
		LISTVIEW_SetItemTextColor(hItem,0,1,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,1,"--");
		LISTVIEW_SetItemText(hItem,5,1,"V");
		LISTVIEW_SetItemTextColor(hItem,5,1,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,2,"电流");
		LISTVIEW_SetItemTextColor(hItem,0,2,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,2,"--");
		LISTVIEW_SetItemText(hItem,5,2,"A");
		LISTVIEW_SetItemTextColor(hItem,5,2,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,3,"功率因数");
		LISTVIEW_SetItemTextColor(hItem,0,3,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,5,3,"--");
		LISTVIEW_SetItemTextColor(hItem,5,3,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,4,"有功功率");
		LISTVIEW_SetItemTextColor(hItem,0,4,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,5,4,"KW");
		LISTVIEW_SetItemTextColor(hItem,5,4,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,5,"无功功率");
		LISTVIEW_SetItemTextColor(hItem,0,5,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,5,5,"KW");
		LISTVIEW_SetItemTextColor(hItem,5,5,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,6,"有功电能");
		LISTVIEW_SetItemTextColor(hItem,0,6,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,5,6,"KWh");
		LISTVIEW_SetItemTextColor(hItem,5,6,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,7,"无功电能");
		LISTVIEW_SetItemTextColor(hItem,0,7,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,5,7,"KWh");
		LISTVIEW_SetItemTextColor(hItem,5,7,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,0,8,"电压THD");
		LISTVIEW_SetItemTextColor(hItem,0,8,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,8,"--");
		LISTVIEW_SetItemText(hItem,5,8,"%");
		LISTVIEW_SetItemTextColor(hItem,5,8,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,0,9,"电流THD");
		LISTVIEW_SetItemTextColor(hItem,0,9,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,9,"--");
		LISTVIEW_SetItemText(hItem,5,9,"%");
		LISTVIEW_SetItemTextColor(hItem,5,9,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontsongti17);
    BUTTON_SetText(hItem,"下一页");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3);
		BUTTON_SetFont(hItem,&GUI_Fontsongti17);
		BUTTON_SetText(hItem,"返回");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
		BUTTON_SetFont(hItem,&GUI_Fontsongti17);
		BUTTON_SetText(hItem,"帮助");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    break;	
	
	case WM_PAINT: 
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,0,480,20);
	  GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,260,480,272);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD) 
	    GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeY) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",100,3);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Font13_1);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		GUI_DispStringAt(SoftVersion,5,4);
			
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
			BUTTON_SetFont(hItem, &GUI_Fontsongti17);
			BUTTON_SetText(hItem,"A母线");
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
			BUTTON_SetFont(hItem, &GUI_Fontsongti17);
			BUTTON_SetText(hItem,"B母线");
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			if(B_BusData==0)
			{
				GUI_DispStringAt("A母线实时数据",360,3);
			}
			else
			{
				GUI_DispStringAt("B母线实时数据",360,3);
			}
	  }
		else 
		{
			GUI_DispStringAt("母线实时数据",360,3);
		}
		break;
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				switch(Id)
					{
					 case ID_BUTTON_0:
						 if(B_BusData==1)
							 B_BusData2=1;
						 else B_BusData2=0;
						  WM_DeleteWindow(hPage[4]);
							hPage[5] = CreateWindowBusData_2(WM_HBKWIN);		//Notifications sent by 'Next_Page'					
              WM_ShowWindow(hPage[5]);					 
						break;
					case ID_BUTTON_1: // Notifications sent by 'A_Data'
						if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
						{
							B_BusData=0;
							WM_InvalidateWindow(pMsg->hWin);
						}
						break;
					case ID_BUTTON_2: // Notifications sent by 'B_Data'
						if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
						{
							B_BusData=1;
							WM_InvalidateWindow(pMsg->hWin);
						}		
						break;
          case ID_BUTTON_3: // Notifications sent by 'Back'
						  B_BusData=0;
					    B_BusData2=0;
							WM_DeleteWindow(hPage[4]);
					    hPage[0]=CreateWindowHome(WM_HBKWIN);					
					    WM_ShowWindow(hPage[0]);
						break;
					case ID_BUTTON_4: // Notifications sent by 'Help'
						  Window_Help_call=1;
						  WM_DeleteWindow(hPage[4]);
              hPage[20]= CreateWindow_Help(WM_HBKWIN);
					    WM_ShowWindow(hPage[20]);
	            					
						break;
         }
       break;
			 }
		break;
	case WM_TIMER:
			Caculate_RTC(pMsg,ID_TEXT_1,ID_TEXT_0);
			if((B_BusData==0)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeD)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeH))
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUa);
				LISTVIEW_SetItemText(hItem,1,0,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUb);
				LISTVIEW_SetItemText(hItem,2,0,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUc);
				LISTVIEW_SetItemText(hItem,3,0,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUab);
				LISTVIEW_SetItemText(hItem,1,1,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUbc);
				LISTVIEW_SetItemText(hItem,2,1,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fUca);
				LISTVIEW_SetItemText(hItem,3,1,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIa);
				LISTVIEW_SetItemText(hItem,1,2,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIb);
				LISTVIEW_SetItemText(hItem,2,2,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fIc);
				LISTVIEW_SetItemText(hItem,3,2,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPFa);
				LISTVIEW_SetItemText(hItem,1,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPFb);
				LISTVIEW_SetItemText(hItem,2,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPFc);
				LISTVIEW_SetItemText(hItem,3,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPFt);
				LISTVIEW_SetItemText(hItem,4,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPa);
				LISTVIEW_SetItemText(hItem,1,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPb);
				LISTVIEW_SetItemText(hItem,2,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPc);
				LISTVIEW_SetItemText(hItem,3,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fPt);
				LISTVIEW_SetItemText(hItem,4,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fQa);
				LISTVIEW_SetItemText(hItem,1,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fQb);
				LISTVIEW_SetItemText(hItem,2,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fQc);
				LISTVIEW_SetItemText(hItem,3,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fQt);
				LISTVIEW_SetItemText(hItem,4,5,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[0].uiEPa)/100));
				LISTVIEW_SetItemText(hItem,1,6,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[0].uiEPb)/100));
				LISTVIEW_SetItemText(hItem,2,6,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[0].uiEPc)/100));
				LISTVIEW_SetItemText(hItem,3,6,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[0].uiEPt)/100));
				LISTVIEW_SetItemText(hItem,4,6,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fEQa);
				LISTVIEW_SetItemText(hItem,1,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fEQb);
				LISTVIEW_SetItemText(hItem,2,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fEQc);
				LISTVIEW_SetItemText(hItem,3,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fEQt);
				LISTVIEW_SetItemText(hItem,4,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fVTHDa);
				LISTVIEW_SetItemText(hItem,1,8,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fVTHDb);
				LISTVIEW_SetItemText(hItem,2,8,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fVTHDc);
				LISTVIEW_SetItemText(hItem,3,8,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fITHDa);
				LISTVIEW_SetItemText(hItem,1,9,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fITHDb);
				LISTVIEW_SetItemText(hItem,2,9,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fITHDc);
				LISTVIEW_SetItemText(hItem,3,9,buf);
			}
			else
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUa);
				LISTVIEW_SetItemText(hItem,1,0,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUb);
				LISTVIEW_SetItemText(hItem,2,0,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUc);
				LISTVIEW_SetItemText(hItem,3,0,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUab);
				LISTVIEW_SetItemText(hItem,1,1,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUbc);
				LISTVIEW_SetItemText(hItem,2,1,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fUca);
				LISTVIEW_SetItemText(hItem,3,1,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fIa);
				LISTVIEW_SetItemText(hItem,1,2,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fIb);
				LISTVIEW_SetItemText(hItem,2,2,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fIc);
				LISTVIEW_SetItemText(hItem,3,2,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPFa);
				LISTVIEW_SetItemText(hItem,1,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPFb);
				LISTVIEW_SetItemText(hItem,2,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPFc);
				LISTVIEW_SetItemText(hItem,3,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPFt);
				LISTVIEW_SetItemText(hItem,4,3,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPa);
				LISTVIEW_SetItemText(hItem,1,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPb);
				LISTVIEW_SetItemText(hItem,2,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPc);
				LISTVIEW_SetItemText(hItem,3,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fPt);
				LISTVIEW_SetItemText(hItem,4,4,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fQa);
				LISTVIEW_SetItemText(hItem,1,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fQb);
				LISTVIEW_SetItemText(hItem,2,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fQc);
				LISTVIEW_SetItemText(hItem,3,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fQt);
				LISTVIEW_SetItemText(hItem,4,5,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[1].uiEPa)/100));
				LISTVIEW_SetItemText(hItem,1,6,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[1].uiEPb)/100));
				LISTVIEW_SetItemText(hItem,2,6,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[1].uiEPc)/100));
				LISTVIEW_SetItemText(hItem,3,6,buf);
				sprintf(buf,"%.2f",(((float)Acq_BusVar_st_a[1].uiEPt)/100));
				LISTVIEW_SetItemText(hItem,4,6,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fEQa);
				LISTVIEW_SetItemText(hItem,1,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fEQb);
				LISTVIEW_SetItemText(hItem,2,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fEQc);
				LISTVIEW_SetItemText(hItem,3,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fEQt);
				LISTVIEW_SetItemText(hItem,4,7,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fVTHDa);
				LISTVIEW_SetItemText(hItem,1,8,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fVTHDb);
				LISTVIEW_SetItemText(hItem,2,8,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fVTHDc);
				LISTVIEW_SetItemText(hItem,3,8,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fITHDa);
				LISTVIEW_SetItemText(hItem,1,9,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fITHDb);
				LISTVIEW_SetItemText(hItem,2,9,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fITHDc);
				LISTVIEW_SetItemText(hItem,3,9,buf);
			}
			WM_RestartTimer(pMsg->Data.v, 100);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
	}
}


static void _cbWindow_BusData_2(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  char buf[30];

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
	  LISTVIEW_SetHeaderHeight(hItem, 22);
	  HEADER_SetTextColor(LISTVIEW_GetHeader(hItem),GUI_BLUE_98);
    HEADER_SetFont(LISTVIEW_GetHeader(hItem),&GUI_Fontsongti17);
    LISTVIEW_AddColumn(hItem, 100, "项目", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 75, "A相/AB", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 75, "B相/BC", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_AddColumn(hItem, 75, "C相/CA", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 75, "合相", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_AddColumn(hItem, 80, "单位", GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
	  LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetRowHeight(hItem,19);
	
		LISTVIEW_SetFont(hItem,&GUI_Fontsongti15);
	  LISTVIEW_SetItemText(hItem,0,0,"最大电流");
		LISTVIEW_SetItemTextColor(hItem,0,0,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,0,"--");
		LISTVIEW_SetItemText(hItem,5,0,"A");
		LISTVIEW_SetItemTextColor(hItem,5,0,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,1,"电流需量");
		LISTVIEW_SetItemTextColor(hItem,0,1,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,1,"--");
		LISTVIEW_SetItemText(hItem,5,1,"A");
		LISTVIEW_SetItemTextColor(hItem,5,1,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,2,"最大电流需量");
		LISTVIEW_SetItemTextColor(hItem,0,2,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,4,2,"--");
		LISTVIEW_SetItemText(hItem,5,2,"A");
		LISTVIEW_SetItemTextColor(hItem,5,2,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,3,"有功需量");
		LISTVIEW_SetItemTextColor(hItem,0,3,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,5,3,"A");
		LISTVIEW_SetItemTextColor(hItem,5,3,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,4,"最大有功需量");
		LISTVIEW_SetItemTextColor(hItem,0,4,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,5,4,"A");
		LISTVIEW_SetItemTextColor(hItem,5,4,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,5,"负载率");
		LISTVIEW_SetItemTextColor(hItem,0,5,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,4,5,"--");
		LISTVIEW_SetItemText(hItem,5,5,"%");
		LISTVIEW_SetItemTextColor(hItem,5,5,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
	  LISTVIEW_SetItemText(hItem,0,6,"频率");
		LISTVIEW_SetItemTextColor(hItem,0,6,LISTVIEW_CI_UNSEL,GUI_BLUE_98);
		LISTVIEW_SetItemText(hItem,1,6,"--");
		LISTVIEW_SetItemText(hItem,2,6,"--");
		LISTVIEW_SetItemText(hItem,3,6,"--");
		LISTVIEW_SetItemText(hItem,5,6,"HZ");
		LISTVIEW_SetItemTextColor(hItem,5,6,LISTVIEW_CI_UNSEL,GUI_BLUE_98);

    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontsongti17);
    BUTTON_SetText(hItem,"上一页");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3);
		BUTTON_SetFont(hItem,&GUI_Fontsongti17);
		BUTTON_SetText(hItem,"返回");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
		BUTTON_SetFont(hItem,&GUI_Fontsongti17);
		BUTTON_SetText(hItem,"帮助");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    break;
		
	case WM_PAINT: 
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,0,480,20);
	  GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,260,480,272);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD) 
	    GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeY) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",100,3);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Font13_1);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		GUI_DispStringAt(SoftVersion,5,4);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
			BUTTON_SetFont(hItem, &GUI_Fontsongti17);
			BUTTON_SetText(hItem,"A母线");
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
			BUTTON_SetFont(hItem, &GUI_Fontsongti17);
			BUTTON_SetText(hItem,"B母线");	
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			if(B_BusData2==0)
			{
				GUI_DispStringAt("A母线实时数据",360,3);
			}
			else
			{
				GUI_DispStringAt("B母线实时数据",360,3);
			}
		}
		else GUI_DispStringAt("母线实时数据",360,3);
			
	
	 break;
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	  switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				switch(Id)
					{
					 case ID_BUTTON_0:
						 if(B_BusData2==1)
							 B_BusData=1;
						 else B_BusData=0;
							hPage[4] = CreateWindowBusData_1(WM_HBKWIN);	
							WM_ShowWindow(hPage[4]);					
							WM_DeleteWindow(hPage[5]);				 
						break;
					case ID_BUTTON_1: // Notifications sent by 'A_Data'
						if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
						{
							B_BusData2=0;
							WM_InvalidateWindow(pMsg->hWin);
						}
						break;
					case ID_BUTTON_2: // Notifications sent by 'B_Data'
						 if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
						{
							B_BusData2=1;
							WM_InvalidateWindow(pMsg->hWin);
						}		
						break;
          case ID_BUTTON_3: // Notifications sent by 'Back'
						  B_BusData=0;
					    B_BusData2=0;
							hPage[0]=CreateWindowHome(WM_HBKWIN);					
							WM_DeleteWindow(hPage[5]);	
              WM_ShowWindow(hPage[0]);					
						break;
					case ID_BUTTON_4: // Notifications sent by 'Help'
              hPage[20]= CreateWindow_Help(WM_HBKWIN);
					    Window_Help_call=2;
					    WM_ShowWindow(hPage[20]);
	            WM_DeleteWindow(hPage[5]);	
						break;
         }
       break;	
			 }
		break;
	case  WM_TIMER://定时器消息,到时间时有效
			Caculate_RTC(pMsg,ID_TEXT_1,ID_TEXT_0);
	    if((B_BusData2==0)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeD)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeH))
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxIa);
				LISTVIEW_SetItemText(hItem,1,0,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxIb);
				LISTVIEW_SetItemText(hItem,2,0,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxIc);
				LISTVIEW_SetItemText(hItem,3,0,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fReqIa);
				LISTVIEW_SetItemText(hItem,1,1,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fReqIb);
				LISTVIEW_SetItemText(hItem,2,1,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fReqIc);
				LISTVIEW_SetItemText(hItem,3,1,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxReqIa);
				LISTVIEW_SetItemText(hItem,1,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxReqIb);
				LISTVIEW_SetItemText(hItem,2,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxReqIc);
				LISTVIEW_SetItemText(hItem,3,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fReqPa);
				LISTVIEW_SetItemText(hItem,1,3,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fReqPb);
				LISTVIEW_SetItemText(hItem,2,3,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fReqPc);
				LISTVIEW_SetItemText(hItem,3,3,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fReqPt);
				LISTVIEW_SetItemText(hItem,4,3,buf);
				LISTVIEW_SetItemText(hItem,3,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxReqPa);
				LISTVIEW_SetItemText(hItem,1,4,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxReqPb);
				LISTVIEW_SetItemText(hItem,2,4,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxReqPc);
				LISTVIEW_SetItemText(hItem,3,4,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[0].fMaxReqPt);
				LISTVIEW_SetItemText(hItem,4,4,buf);
				sprintf(buf,"%.2f",((float)Acq_BusVar_st_a[0].fIa/(float)Optimset_st.usRateI[0]));
				LISTVIEW_SetItemText(hItem,1,5,buf);
				sprintf(buf,"%.2f",((float)Acq_BusVar_st_a[0].fIb/(float)Optimset_st.usRateI[0]));
				LISTVIEW_SetItemText(hItem,2,5,buf);
				sprintf(buf,"%.2f",((float)Acq_BusVar_st_a[0].fIc/(float)Optimset_st.usRateI[0]));
				LISTVIEW_SetItemText(hItem,3,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[0].fF);
				LISTVIEW_SetItemText(hItem,4,6,buf);
	  	}
			else
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxIa);
				LISTVIEW_SetItemText(hItem,1,0,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxIb);
				LISTVIEW_SetItemText(hItem,2,0,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxIc);
				LISTVIEW_SetItemText(hItem,3,0,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fReqIa);
				LISTVIEW_SetItemText(hItem,1,1,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fReqIb);
				LISTVIEW_SetItemText(hItem,2,1,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fReqIc);
				LISTVIEW_SetItemText(hItem,3,1,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxReqIa);
				LISTVIEW_SetItemText(hItem,1,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxReqIb);
				LISTVIEW_SetItemText(hItem,2,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxReqIc);
				LISTVIEW_SetItemText(hItem,3,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fReqPa);
				LISTVIEW_SetItemText(hItem,1,3,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fReqPb);
				LISTVIEW_SetItemText(hItem,2,3,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fReqPc);
				LISTVIEW_SetItemText(hItem,3,3,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fReqPt);
				LISTVIEW_SetItemText(hItem,4,3,buf);
				LISTVIEW_SetItemText(hItem,3,2,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxReqPa);
				LISTVIEW_SetItemText(hItem,1,4,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxReqPb);
				LISTVIEW_SetItemText(hItem,2,4,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxReqPc);
				LISTVIEW_SetItemText(hItem,3,4,buf);
				sprintf(buf,"%.2f",Ana_BusVar_st_a[1].fMaxReqPt);
				LISTVIEW_SetItemText(hItem,4,4,buf);
				sprintf(buf,"%.2f",((float)Acq_BusVar_st_a[1].fIa/(float)Optimset_st.usRateI[1]));
				LISTVIEW_SetItemText(hItem,1,5,buf);
				sprintf(buf,"%.2f",((float)Acq_BusVar_st_a[1].fIb/(float)Optimset_st.usRateI[1]));
				LISTVIEW_SetItemText(hItem,2,5,buf);
				sprintf(buf,"%.2f",((float)Acq_BusVar_st_a[1].fIc/(float)Optimset_st.usRateI[1]));
				LISTVIEW_SetItemText(hItem,3,5,buf);
				sprintf(buf,"%.2f",Acq_BusVar_st_a[1].fF);
				LISTVIEW_SetItemText(hItem,4,6,buf);
			}
			WM_RestartTimer(pMsg->Data.v, 100);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
   }		
}



WM_HWIN CreateWindowBusData_1(WM_HWIN hParent);
WM_HWIN CreateWindowBusData_1(WM_HWIN hParent) {

  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_BusData_1, GUI_COUNTOF(_BusData_1), _cbWindow_BusData_1, WM_HBKWIN, 0, 0);
  WM_CreateTimer(WM_GetClientWindow(hWin),0,200,0);
  return hWin;
}

WM_HWIN CreateWindowBusData_2(WM_HWIN hParent);
WM_HWIN CreateWindowBusData_2(WM_HWIN hParent) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_BusData_2, GUI_COUNTOF(_BusData_2), _cbWindow_BusData_2, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,200,0);
  return hWin;
}

/*************************** End of file ****************************/
