/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include.h"
#include "sys_Variable.h"
#include "app_PTEnergy.h"
#include "app_Optimset.h"
#include "cmsis_os.h"
#include <string.h>
#include <stdlib.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_1    (GUI_ID_USER + 0x02)
#define ID_TEXT_2    (GUI_ID_USER + 0x03)
#define ID_TEXT_3    (GUI_ID_USER + 0x04)
#define ID_TEXT_4    (GUI_ID_USER + 0x05)
#define ID_TEXT_5    (GUI_ID_USER + 0x06)
#define ID_TEXT_6    (GUI_ID_USER + 0x07)
#define ID_EDIT_0    (GUI_ID_USER + 0x08)
#define ID_EDIT_1    (GUI_ID_USER + 0x09)
#define ID_EDIT_2    (GUI_ID_USER + 0x0A)
#define ID_EDIT_3    (GUI_ID_USER + 0x0B)
#define ID_TEXT_7    (GUI_ID_USER + 0x0C)
#define ID_TEXT_8    (GUI_ID_USER + 0x0D)
#define ID_TEXT_9    (GUI_ID_USER + 0x0E)
#define ID_TEXT_10    (GUI_ID_USER + 0x0F)
#define ID_TEXT_11    (GUI_ID_USER + 0x10)
#define ID_TEXT_12    (GUI_ID_USER + 0x11)
#define ID_TEXT_13    (GUI_ID_USER + 0x12)
#define ID_TEXT_14    (GUI_ID_USER + 0x13)
#define ID_BUTTON_0    (GUI_ID_USER + 0x14)
#define ID_BUTTON_1    (GUI_ID_USER + 0x15)
#define ID_BUTTON_2    (GUI_ID_USER + 0x16)
#define ID_BUTTON_3    (GUI_ID_USER + 0x17)
#define ID_BUTTON_4    (GUI_ID_USER + 0x18)
#define ID_BUTTON_5    (GUI_ID_USER + 0x19)
#define ID_BUTTON_6    (GUI_ID_USER + 0x1A)
#define ID_LISTVIEW_0    (GUI_ID_USER + 0x1B)
#define ID_TEXT_15    (GUI_ID_USER + 0x1C)
#define ID_TEXT_16    (GUI_ID_USER + 0x1D)
#define ID_TEXT_17    (GUI_ID_USER + 0x1E)
#define ID_TEXT_18    (GUI_ID_USER + 0x1F)
#define ID_TEXT_19    (GUI_ID_USER + 0x20)
#define ID_TEXT_20    (GUI_ID_USER + 0x21)
#define ID_TEXT_21    (GUI_ID_USER + 0x22)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _HistoryEnergy_1[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 1, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Energy_Inquiry_Period", ID_TEXT_0, 160, 22, 136, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Start_Time_Text", ID_TEXT_1, 19, 47, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "End_Time_Text", ID_TEXT_2, 260, 47, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Year", ID_TEXT_3, 130, 47, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Month", ID_TEXT_4, 200, 47, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Year", ID_TEXT_5, 370, 47, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Month", ID_TEXT_6, 440, 47, 20, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Start_Year", ID_EDIT_0, 85, 45, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Start_Month", ID_EDIT_1, 155, 45, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "End_Year", ID_EDIT_2, 325, 45, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "End_Month", ID_EDIT_3, 396, 45, 40, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "A_Text", ID_TEXT_7, 110, 77, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "B_Text", ID_TEXT_8, 110, 102, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "C_Text", ID_TEXT_9, 110, 127, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sum", ID_TEXT_10, 110, 152, 80, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_17, 210, 77, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_18, 210, 102, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_19, 210, 127, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_20, 210, 152, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "KWh", ID_TEXT_11, 330, 77, 35, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "KWh", ID_TEXT_12, 330, 102, 35, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "KWh", ID_TEXT_13, 330, 127, 35, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "KWh", ID_TEXT_14, 330, 152, 35, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Heip", ID_BUTTON_0, 410, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_1, 342, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_2, 274, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next_Page", ID_BUTTON_3, 206, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_4, 138, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_5, 70, 236, 67, 23, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "A_Bus", ID_BUTTON_6, 2, 234, 67, 23, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 1, 171, 478, 61, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_15, 428,259, 45, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_16, 360, 259, 55, 15, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_21, 225, 259, 53, 15, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

static const GUI_WIDGET_CREATE_INFO _HistoryEnergy_2[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 1, 0, 480, 272, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "Heip", ID_BUTTON_0, 410, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_1, 342, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next_Page", ID_BUTTON_2, 274, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Last_Page", ID_BUTTON_3, 206, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_4, 138, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_5, 70, 236, 67, 23, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 1, 21, 478, 209, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_15, 428,259, 45, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_16, 360, 259, 55, 15, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_21, 225, 259, 53, 15, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};


static uint16_t STime=0,ETime=0;
static PTEnergyTypeDef   PTEnergy={0};
static uint8_t SaveEnergy;
extern WM_HWIN hPage[25];
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti15;
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti17;


void PTE_Dispalay(GUI_HWIN hItem,uint8_t Bflag, uint8_t row, PTEnergyTypeDef  *PTEnergy)
{
   char buf[30];
			
   sprintf(buf,"%0.2d/%0.2d/%0.2d",(PTEnergy->Time>>8)&0xFF,PTEnergy->Time&0xFF, 0x01);
          LISTVIEW_SetItemText(hItem,0,row,buf);
	 if(Bflag == 0)
		{
				sprintf(buf, "%.2f", (float)PTEnergy->EP[0]/100);
				LISTVIEW_SetItemText(hItem,1,row,buf);
				
				sprintf(buf, "%.2f", (float)PTEnergy->EP[1]/100);
				LISTVIEW_SetItemText(hItem,2,row,buf);
				
				sprintf(buf, "%.2f", (float)PTEnergy->EP[2]/100);
				LISTVIEW_SetItemText(hItem,3,row,buf);
				
				sprintf(buf, "%.2f", (float)PTEnergy->EP[3]/100);
				LISTVIEW_SetItemText(hItem,4,row,buf);							
		}
		else if(Bflag == 1)
		{
				sprintf(buf, "%.2f", (float)PTEnergy->EP[4]/100);
				LISTVIEW_SetItemText(hItem,1,row,buf);
				
				sprintf(buf, "%.2f", (float)PTEnergy->EP[5]/100);
				LISTVIEW_SetItemText(hItem,2,row,buf);
				
				sprintf(buf, "%.2f", (float)PTEnergy->EP[6]/100);
				LISTVIEW_SetItemText(hItem,3,row,buf);
				
				sprintf(buf, "%.2f", (float)PTEnergy->EP[7]/100);
				LISTVIEW_SetItemText(hItem,4,row,buf);							
		}	
}


void PTE_Get(GUI_HWIN hItem,uint8_t page,uint8_t Bflag)
{
   struct PTEnergyTypeDef  PTEnergy;
	 
   uint8_t i;
	 uint16_t FMAddr;
	 
	 if(SaveEnergy > 0)
	 {
	     if(page == 0)
			 {
					if(SaveEnergy>1)
					{
							for(i = 0; i < 2; i++)
							{
									FMAddr = FMAddr_EP_PastTime + FMOffset_PTE+(SaveEnergy-1-i)*sizeof(struct PTEnergyTypeDef);
									
									taskENTER_CRITICAL();
									Fram_I2C_Read((uint8_t *)&PTEnergy, FMAddr, sizeof(struct PTEnergyTypeDef));
									taskEXIT_CRITICAL();
									
									PTE_Dispalay(hItem, Bflag, i, &PTEnergy);					
							} 
					}
					else
					{
							FMAddr = FMAddr_EP_PastTime + FMOffset_PTE;
							
							taskENTER_CRITICAL();
							Fram_I2C_Read((uint8_t *)&PTEnergy, FMAddr, sizeof(struct PTEnergyTypeDef));
							taskEXIT_CRITICAL();
							
							PTE_Dispalay(hItem, Bflag, 0, &PTEnergy);	
					}
					
			 }
			 else
			 {
			 
					if((page + 1) <= (SaveEnergy-2)/10)
					{
							for(i = 0; i < 10; i++)
							{
									FMAddr = FMAddr_EP_PastTime + FMOffset_PTE+(SaveEnergy-3-((page-1)*10)-i)*sizeof(struct PTEnergyTypeDef);
									
									taskENTER_CRITICAL();
									Fram_I2C_Read((uint8_t *)&PTEnergy, FMAddr, sizeof(struct PTEnergyTypeDef));
									taskEXIT_CRITICAL();
									
									PTE_Dispalay(hItem, Bflag, i, &PTEnergy);  					
							}  
					}
					else
					{ 			
							if((SaveEnergy-2)%10)
							{
									for(i = 0; i < (SaveEnergy-2)%10; i++)
									{
											FMAddr = FMAddr_EP_PastTime + FMOffset_PTE+(SaveEnergy-3-((page-1)*10)-i)*sizeof(struct PTEnergyTypeDef);
											
											taskENTER_CRITICAL();
											Fram_I2C_Read((uint8_t *)&PTEnergy, FMAddr, sizeof(struct PTEnergyTypeDef)); 
											taskEXIT_CRITICAL();
											
											PTE_Dispalay(hItem, Bflag, i, &PTEnergy);   
									}					
							} 
					} 
			 }	 
	 }
	 
}

static void _cbHistory_Energy_1(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	char buf[30],Month[2];
  static uint8_t Pagenum =0, Maxpage=0,B_Energy=0;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetFont(hItem, &GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",(STime>>8)&0xFF);
		EDIT_SetText(hItem,buf);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetFont(hItem, &GUI_Fontsongti15);
		sprintf(buf,"%d",STime&0xFF);
		EDIT_SetText(hItem,buf);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetFont(hItem,&GUI_Fontsongti15);
		sprintf(buf,"%d",(ETime>>8)&0xFF);
		EDIT_SetText(hItem,buf);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetFont(hItem,&GUI_Fontsongti15);
		sprintf(buf,"%d",ETime&0xFF);
		EDIT_SetText(hItem,buf);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti15);
		TEXT_SetText(hItem,"电能查询时间段设置");
		TEXT_SetTextColor(hItem,GUI_BLUE_98);	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti15);
		TEXT_SetText(hItem,"开始时间");
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti15);
		TEXT_SetText(hItem,"结束时间");
		TEXT_SetTextColor(hItem,GUI_BLUE_98);	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti15);
		TEXT_SetText(hItem,"年");
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti15);
		TEXT_SetText(hItem,"月");
		TEXT_SetTextColor(hItem,GUI_BLUE_98);	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti15);
		TEXT_SetText(hItem,"年");
		TEXT_SetTextColor(hItem,GUI_BLUE_98);	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti15);
		TEXT_SetText(hItem,"月");
		TEXT_SetTextColor(hItem,GUI_BLUE_98);		
		
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER  | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
		TEXT_SetTextColor(hItem,GUI_BLUE_98); 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER  | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1); 
		TEXT_SetTextColor(hItem,GUI_BLUE_98); 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER  | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
		TEXT_SetTextColor(hItem,GUI_BLUE_98); 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER  | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
		TEXT_SetTextColor(hItem,GUI_BLUE_98); 
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti17);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti17);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti17);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_Fontsongti17);
    
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"帮助");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"返回");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"下一页");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"确定");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		HEADER_SetTextColor(LISTVIEW_GetHeader(hItem),GUI_BLUE_98);
		HEADER_SetFont(LISTVIEW_GetHeader(hItem),&GUI_Fontsongti15);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_SetGridVis(hItem, 1);
		LISTVIEW_SetRowHeight(hItem, 20);	
		LISTVIEW_SetFont(hItem,&GUI_Fontsongti15);
		LISTVIEW_AddColumn(hItem, 96, "时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTVIEW_AddColumn(hItem, 96, "A相", GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTVIEW_AddColumn(hItem, 96, "B相", GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTVIEW_AddColumn(hItem, 96, "C相", GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTVIEW_AddColumn(hItem, 96, "合相", GUI_TA_HCENTER | GUI_TA_VCENTER);
		for(int i=0;i<2;i++)
		{
			LISTVIEW_DisableRow(hItem,i);
			for(int j=0;j<5;j++)
			{
				LISTVIEW_SetItemBkColor(hItem,j,i,LISTVIEW_CI_DISABLED,GUI_WHITE);
			}
		}	
    break;
	
	case WM_PAINT: 
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,0,480,20);
	  GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,260,480,272);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD) 
	    GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeY) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",100,3);
	
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Font13_1);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		GUI_DispStringAt(SoftVersion,5,4);
			
		
		SaveEnergy=gPTE_GetIndex();
		if(SaveEnergy<=2)
		{
		   Maxpage = 1;
			 Pagenum = 0;	 
		}
		else
		{
		   if((SaveEnergy-2)%10)
			 {
			    Maxpage =  (SaveEnergy-2)/10 + 2;
			 }
			 else
			 {
			    Maxpage =  (SaveEnergy-2)/10 + 1;
			 }
	  }
		sprintf(buf,"%d / %d",Pagenum+1,Maxpage);
		TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_21),buf);
		TEXT_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_TEXT_21),GUI_WHITE);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
			BUTTON_SetFont(hItem, &GUI_Fontsongti15);
			BUTTON_SetText(hItem,"B母线");
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
			BUTTON_SetFont(hItem, &GUI_Fontsongti15);
			BUTTON_SetText(hItem,"A母线");
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			if(B_Energy==1)
			{
				GUI_DispStringAt("B母线历史电能",360,3);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"B母线 A相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98);	
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"B母线 B相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98);	
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"B母线 C相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98);	
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"B母线合相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98); 
				
		 }
			else
			{
				GUI_DispStringAt("A母线历史电能",360,3);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"A母线 A相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98);	
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"A母线 B相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98);	
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"A母线 C相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98);	
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
				TEXT_SetFont(hItem, &GUI_Fontsongti15);
				TEXT_SetText(hItem,"A母线合相");
				TEXT_SetTextColor(hItem,GUI_BLUE_98); 
			}
	  }
		else
		{
			GUI_DispStringAt("母线历史电能",360,3);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
			TEXT_SetFont(hItem, &GUI_Fontsongti15);
			TEXT_SetText(hItem,"母线 A相");
			TEXT_SetTextColor(hItem,GUI_BLUE_98);	
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
			TEXT_SetFont(hItem, &GUI_Fontsongti15);
			TEXT_SetText(hItem,"母线 B相");
			TEXT_SetTextColor(hItem,GUI_BLUE_98);	
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
			TEXT_SetFont(hItem, &GUI_Fontsongti15);
			TEXT_SetText(hItem,"母线 C相");
			TEXT_SetTextColor(hItem,GUI_BLUE_98);	
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
			TEXT_SetFont(hItem, &GUI_Fontsongti15);
			TEXT_SetText(hItem,"母线合相");
			TEXT_SetTextColor(hItem,GUI_BLUE_98); 
		}
	
		break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	  switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
					if((Id>=ID_EDIT_0)&&(Id<=ID_EDIT_3))
				{
					 if(Keyboard_Call==0) hPage[13] = CreateWindowNumberpad(hPage[14]);
						EDIT_SetText(WM_GetDialogItem(pMsg->hWin, Id),"");
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
						Keyboard_Call+=1;
				}
				switch(Id) {
          case ID_BUTTON_0: // Notifications sent by 'Heip'
						 WM_DeleteWindow(hPage[14]);
					   Window_Help_call=0x05;
             hPage[20]= CreateWindow_Help(WM_HBKWIN);
					   WM_ShowWindow(hPage[20]);
            break;
					case ID_BUTTON_1: // Notifications sent by 'Back'
						WM_DeleteWindow(hPage[14]);
						hPage[0]=CreateWindowHome(WM_HBKWIN);
					  WM_ShowWindow(hPage[0]);
					 break;
         case ID_BUTTON_3: // Notifications sent by 'OK'
				     EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), buf, sizeof(buf)); //开始年
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1), Month, sizeof(Month)); //开始月
						 STime = (atoi(buf)<<8)|atoi(Month); 
						 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2), buf, sizeof(buf)); //结束年
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_3), Month, sizeof(Month)); //结束月
						 ETime = (atoi(buf)<<8)|atoi(Month);

             gPTE_Query(STime, ETime, &PTEnergy);						 


           break;
         case ID_BUTTON_2: // Notifications sent by 'Next_Page'
				    if(Maxpage>1)
				    {
							WM_DeleteWindow(hPage[14]);
							hPage[15] = CreateWindowAHistory_Energy_2(WM_HBKWIN);
							WM_ShowWindow(hPage[15]);
						}
           break;
         case ID_BUTTON_4: // Notifications sent by 'B_Bus'
					 if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
					 {
             B_Energy=1;
				     WM_InvalidateWindow(pMsg->hWin);
					 }
           break;
         case ID_BUTTON_5: // Notifications sent by 'A_Bus'
				   if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
					 {
					   B_Energy=0;
				     WM_InvalidateWindow(pMsg->hWin);
					 }
           break;
      }
      break;
    }
    break;
	case WM_TIMER:
		Caculate_RTC(pMsg,ID_TEXT_16,ID_TEXT_15);
		if((B_Energy==0)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeD)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeH))
		{
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[0])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_17),buf);
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[1])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_18),buf);
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[2])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_19),buf);
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[3])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_20),buf);
			PTE_Get(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),Pagenum,0);	
		}
		else
		{
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[4])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_17),buf);
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[5])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_18),buf);
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[6])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_19),buf);
			sprintf(buf,"%.2f",(((float)PTEnergy.EP[7])/100));
			TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_20),buf);
			PTE_Get(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),Pagenum,1);
		}
		WM_RestartTimer(pMsg->Data.v, 100);
		break;			
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

static void _cbHistory_Energy_2(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	char buf[30];
	static uint8_t Pagenum =1, Maxpage=0,B_Energy_2=0;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
	  HEADER_SetTextColor(LISTVIEW_GetHeader(hItem),GUI_BLUE_98);
		HEADER_SetFont(LISTVIEW_GetHeader(hItem),&GUI_Fontsongti15);
		LISTVIEW_AddColumn(hItem, 96, "时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTVIEW_AddColumn(hItem, 96, "A相", GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTVIEW_AddColumn(hItem, 96, "B相", GUI_TA_HCENTER | GUI_TA_VCENTER);	
		LISTVIEW_AddColumn(hItem, 96, "C相", GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTVIEW_AddColumn(hItem, 96, "合相", GUI_TA_HCENTER | GUI_TA_VCENTER);
	  LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_SetGridVis(hItem, 1);
	  LISTVIEW_SetRowHeight(hItem, 19);
		for(int i=0;i<10;i++)
		{
			LISTVIEW_DisableRow(hItem,i);
			for(int j=0;j<6;j++)
			{
				LISTVIEW_SetItemBkColor(hItem,j,i,LISTVIEW_CI_DISABLED,GUI_WHITE);
			}
		}
    LISTVIEW_SetFont(hItem,&GUI_Fontsongti15);
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"帮助");
	  BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"返回");
	  BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"下一页");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
  	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_Fontsongti15);
    BUTTON_SetText(hItem,"上一页");	
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
	  
    break;
	
	case WM_PAINT: 
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,0,480,20);
	  GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRect(0,260,480,272);
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD) 
	    GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeY) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",100,3);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH) 
			GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",100,3);
	
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Font13_1);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		GUI_DispStringAt(SoftVersion,5,4);
			
		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(&GUI_Fontsongti15);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
		{
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
			BUTTON_SetFont(hItem, &GUI_Fontsongti15);
			BUTTON_SetText(hItem,"B母线");
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
			BUTTON_SetFont(hItem, &GUI_Fontsongti15);
			BUTTON_SetText(hItem,"A母线");	
			BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
			if(B_Energy_2==0)
				GUI_DispStringAt("A母线历史电能",360,3);
			else
				GUI_DispStringAt("B母线历史电能",360,3);
	  }
		else
		{
			GUI_DispStringAt("母线历史电能",360,3);
		}
	  if((SaveEnergy-2)%10)
	  {
			Maxpage =  (SaveEnergy-2)/10 + 2;
	  }
	  else
	  {
	 		Maxpage =  (SaveEnergy-2)/10 + 1;
	  }
		sprintf(buf,"%d / %d",Pagenum+1,Maxpage);
		TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_21),buf);
		TEXT_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_TEXT_21),GUI_WHITE);
		
		break;
		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
	  switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
				switch(Id) {
				case ID_BUTTON_0: // Notifications sent by 'Heip'
					  WM_DeleteWindow(hPage[15]);
				    Window_Help_call=0x06;
					  hPage[20]= CreateWindow_Help(WM_HBKWIN);
					  WM_ShowWindow(hPage[20]);
					break;
				case ID_BUTTON_1: // Notifications sent by 'Back'
					 WM_DeleteWindow(hPage[15]); 
					 hPage[14] = CreateWindowAHistory_Energy_1(WM_HBKWIN);
					 WM_ShowWindow(hPage[14]);
					break;
				case ID_BUTTON_2: // Notifications sent by 'Next_Page'
						if(Pagenum<Maxpage-1)
						Pagenum++;
						 WM_InvalidateWindow(pMsg->hWin);
					break;
				case ID_BUTTON_3: // Notifications sent by 'Last_Page'
					  if(Pagenum==1)
					  {
							WM_DeleteWindow(hPage[15]);
							hPage[14] = CreateWindowAHistory_Energy_1(WM_HBKWIN);
							WM_ShowWindow(hPage[14]);
						}
						else
						{
							Pagenum--;
						  WM_InvalidateWindow(pMsg->hWin);
						}
					break;
				case ID_BUTTON_4: // Notifications sent by 'B_Bus'
					  if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
						{
						  B_Energy_2=1;
				      WM_InvalidateWindow(pMsg->hWin);
						}
				 	break;
				case ID_BUTTON_5: // Notifications sent by 'A_Bus'
					  if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
						{
					    B_Energy_2=0;
				  	  WM_InvalidateWindow(pMsg->hWin);
						} 
					 	break;
					}
					break;
				}
			 break;
	case WM_TIMER:
		Caculate_RTC(pMsg,ID_TEXT_16,ID_TEXT_15);
	  if((Optimset_st.Setup.Setup_st.bBusMode==BusModeS)||(Optimset_st.Setup.Setup_st.bBusMode==BusModeY))
		{
			if(B_Energy_2==0)
				PTE_Get(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),Pagenum,0);
			else
				PTE_Get(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),Pagenum,1);
	  }
		else
			PTE_Get(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),Pagenum,0);
	  WM_RestartTimer(pMsg->Data.v, 100);
 		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}





WM_HWIN CreateWindowAHistory_Energy_1(WM_HWIN hParent);
WM_HWIN CreateWindowAHistory_Energy_1(WM_HWIN hParent) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_HistoryEnergy_1, GUI_COUNTOF(_HistoryEnergy_1), _cbHistory_Energy_1, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,200,0);
  return hWin;
}

WM_HWIN CreateWindowAHistory_Energy_2(WM_HWIN hParent);
WM_HWIN CreateWindowAHistory_Energy_2(WM_HWIN hParent) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_HistoryEnergy_2, GUI_COUNTOF(_HistoryEnergy_2), _cbHistory_Energy_2, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,200,0);
  return hWin;
}

/*************************** End of file ****************************/
