/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "include.h"
#include "app_PCProto.h"
#include "app_Optimset.h"
#include "sys_Variable.h"
#include "app_Optimset.h"
#include <stdlib.h>
#include "bsp_RTC.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_1   (GUI_ID_USER + 0x02)
#define ID_BUTTON_2   (GUI_ID_USER + 0x03)
#define ID_EDIT_6     (GUI_ID_USER + 0x05)
#define ID_EDIT_1     (GUI_ID_USER + 0x06)
#define ID_EDIT_2     (GUI_ID_USER + 0x07)
#define ID_EDIT_3     (GUI_ID_USER + 0x08)
#define ID_EDIT_4     (GUI_ID_USER + 0x09)
#define ID_EDIT_5     (GUI_ID_USER + 0x0A)
#define ID_EDIT_0     (GUI_ID_USER + 0x0B)
#define ID_EDIT_7     (GUI_ID_USER + 0x0C)
#define ID_EDIT_8     (GUI_ID_USER + 0x0D)
#define ID_EDIT_9     (GUI_ID_USER + 0x0E)
#define ID_EDIT_10    (GUI_ID_USER + 0x0F)
#define ID_EDIT_11    (GUI_ID_USER + 0x10)
#define ID_EDIT_12    (GUI_ID_USER + 0x11)
#define ID_EDIT_13    (GUI_ID_USER + 0x12)
#define ID_EDIT_14    (GUI_ID_USER + 0x13)
#define ID_EDIT_15    (GUI_ID_USER + 0x14)
#define ID_EDIT_16    (GUI_ID_USER + 0x15)
#define ID_EDIT_17    (GUI_ID_USER + 0x16)
#define ID_EDIT_18    (GUI_ID_USER + 0x17)
#define ID_EDIT_19    (GUI_ID_USER + 0x18)
#define ID_EDIT_20    (GUI_ID_USER + 0x19)
#define ID_EDIT_21    (GUI_ID_USER + 0x1A)
#define ID_EDIT_22    (GUI_ID_USER + 0x1B)
#define ID_EDIT_23    (GUI_ID_USER + 0x1C)
#define ID_EDIT_24    (GUI_ID_USER + 0x1D)
#define ID_EDIT_25    (GUI_ID_USER + 0x1E)
#define ID_EDIT_26    (GUI_ID_USER + 0x1F)
#define ID_EDIT_27    (GUI_ID_USER + 0x20)
#define ID_EDIT_28    (GUI_ID_USER + 0x21)
#define ID_EDIT_29    (GUI_ID_USER + 0x22)
#define ID_EDIT_30    (GUI_ID_USER + 0x23)
#define ID_EDIT_31    (GUI_ID_USER + 0x24)
#define ID_EDIT_32    (GUI_ID_USER + 0x25)
#define ID_TEXT_0     (GUI_ID_USER + 0x26)
#define ID_TEXT_1     (GUI_ID_USER + 0x27)
#define ID_TEXT_2     (GUI_ID_USER + 0x28)
#define ID_TEXT_3     (GUI_ID_USER + 0x29)
#define ID_TEXT_4     (GUI_ID_USER + 0x2A)
#define ID_TEXT_5     (GUI_ID_USER + 0x2B)
#define ID_DROPDOWN_0    (GUI_ID_USER + 0x2C)  
#define ID_TEXT_6     (GUI_ID_USER + 0x2D)
#define ID_TEXT_7     (GUI_ID_USER + 0x2E)
#define ID_TEXT_8     (GUI_ID_USER + 0x2F)
#define ID_TEXT_9     (GUI_ID_USER + 0x30)
#define ID_TEXT_10    (GUI_ID_USER + 0x31)
#define ID_TEXT_11    (GUI_ID_USER + 0x32)
#define ID_TEXT_12    (GUI_ID_USER + 0x33)
#define ID_TEXT_13    (GUI_ID_USER + 0x34)
#define ID_TEXT_14    (GUI_ID_USER + 0x35)
#define ID_TEXT_15    (GUI_ID_USER + 0x36)
#define ID_TEXT_16    (GUI_ID_USER + 0x37)
#define ID_TEXT_17    (GUI_ID_USER + 0x38)
#define ID_TEXT_18    (GUI_ID_USER + 0x39)
#define ID_TEXT_19    (GUI_ID_USER + 0x3A)
#define ID_TEXT_20    (GUI_ID_USER + 0x3B)
#define ID_TEXT_21    (GUI_ID_USER + 0x3C)
#define ID_TEXT_22    (GUI_ID_USER + 0x3D)
#define ID_TEXT_23    (GUI_ID_USER + 0x3E)
#define ID_TEXT_24    (GUI_ID_USER + 0x3F)
#define ID_TEXT_25    (GUI_ID_USER + 0x40)
#define ID_TEXT_26    (GUI_ID_USER + 0x41)
#define ID_TEXT_27    (GUI_ID_USER + 0x42)
#define ID_TEXT_28    (GUI_ID_USER + 0x43)
#define ID_TEXT_29    (GUI_ID_USER + 0x44)
#define ID_TEXT_30    (GUI_ID_USER + 0x45)
#define ID_TEXT_31    (GUI_ID_USER + 0x46)
#define ID_TEXT_32    (GUI_ID_USER + 0x47)
#define ID_TEXT_33    (GUI_ID_USER + 0x48)
#define ID_TEXT_34    (GUI_ID_USER + 0x49)
#define ID_TEXT_35    (GUI_ID_USER + 0x4A)
/*********************************************************************
*
*       _aDialogCreate
*/
extern WM_HWIN hPage[25];
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti15;
static const GUI_WIDGET_CREATE_INFO _DeviceInform[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Help", ID_BUTTON_0, 410, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_1, 342, 236, 67, 23, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Set", ID_BUTTON_2, 274, 236, 67, 23, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Year", ID_EDIT_0, 25, 28, 48, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Month", ID_EDIT_1, 97, 28, 48, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Data", ID_EDIT_2, 169, 28, 48, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Year_Text", ID_TEXT_0, 75, 30, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Month_Text", ID_TEXT_1, 147, 30, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Data_Text", ID_TEXT_2, 219, 30, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Hour_Text", ID_TEXT_3, 291, 30, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Minute_Text", ID_TEXT_4, 363, 30, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Second_Text", ID_TEXT_5, 435, 30, 20, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Hour", ID_EDIT_3, 241, 28, 48, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Minute", ID_EDIT_4, 313, 28, 48, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Second", ID_EDIT_5, 385, 28, 48, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Device_Code", ID_EDIT_6, 117, 55, 133, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "IP_Addr_0", ID_EDIT_7, 337, 55, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "IP_Addr_1", ID_EDIT_21, 371, 55, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "IP_Addr_2", ID_EDIT_22, 405, 55, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "IP_Addr_3", ID_EDIT_23, 439, 55, 31, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_24, 368, 55, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_25, 402, 55, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_26, 436, 55, 3, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Subnet_Mask_0", ID_EDIT_8, 337, 80,31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Subnet_Mask_1", ID_EDIT_27, 371, 80, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Subnet_Mask_2", ID_EDIT_28, 405, 80, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Subnet_Mask_3", ID_EDIT_29, 439, 80, 31, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_27, 368, 80, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_28, 402, 80, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_29, 436, 80, 3, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Gateway", ID_EDIT_9, 337, 105, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Gateway", ID_EDIT_30, 371, 105, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Gateway", ID_EDIT_31, 405, 105, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Gateway", ID_EDIT_32, 439, 105, 31, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_30, 368, 105, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_31, 402, 105, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_32, 436, 105, 3, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Remote_Port", ID_EDIT_10, 337, 130, 133, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Commucate_Addr", ID_EDIT_11, 117, 80, 133, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Remote_IP_0", ID_EDIT_12, 117, 130, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Remote_IP_1", ID_EDIT_24, 153, 130, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Remote_IP_2", ID_EDIT_25, 187, 130, 31, 20, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Remote_IP_3", ID_EDIT_26, 221, 130, 31, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_33, 148, 130, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_34, 184, 130, 3, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, ".", ID_TEXT_35, 218, 130, 3, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Baud_Rate", ID_DROPDOWN_0 , 117, 105, 133, 85, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Device_Code_Text", ID_TEXT_6, 30, 57, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Commucate_Addr_Text", ID_TEXT_7, 20, 82, 90, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Baud_Rate_Text", ID_TEXT_8, 30, 107, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Remote_IP_Text", ID_TEXT_9, 30, 132, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "IP_Addr_Text", ID_TEXT_10, 275, 57, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Subnet_Mask_Text", ID_TEXT_11, 275, 82, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Gateway_Text", ID_TEXT_12, 275, 107, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Port_Text", ID_TEXT_13, 275, 132, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "V_Low_Text", ID_TEXT_14, 35, 162, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "I_High1_Text", ID_TEXT_15, 5, 187, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "I_High2_Text", ID_TEXT_16, 5, 212, 110, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "V_Low", ID_EDIT_13, 117, 160, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "I_High1", ID_EDIT_14, 117, 185, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "I_High2", ID_EDIT_15, 117, 210, 40, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Pa_Threshold_Text", ID_TEXT_17, 312, 162, 115, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Pa_Threshold", ID_EDIT_16, 430, 160, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "V_High", ID_EDIT_17, 258, 160, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Frequency_Low", ID_EDIT_18, 258, 185, 40, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Frequency_High", ID_EDIT_19, 258, 210, 40, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "V_High_Text", ID_TEXT_18, 173, 162, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Frequency_High_Text", ID_TEXT_19, 168, 212, 90, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Frequency_Low_Text", ID_TEXT_20, 168, 185, 90, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Pb_Threshold_Text", ID_TEXT_21, 312, 185, 115, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Pb_Threshold", ID_EDIT_20, 430, 185, 40, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_22, 428,259, 45, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_23, 360, 259, 55, 15, 0, 0x64, 0 },
};

uint8_t Keyboard_Call=0;
static void _cbDevice_Inform(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	
	RTC_TimeTypeDef    sTime;
	RTC_DateTypeDef    sDate;
	 
  int     NCode;
  int     Id;
	int     i;
  static char  buf[5]="0";	
	static int DropdownSecItemNum=0;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_WINDOW_0);
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"年");
	  
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"月");
	
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"日");
	
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"时");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"分");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"秒");
    // Initialization of 'Year'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'Month'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'Data'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'Hour'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'Minute'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'Second'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'Device_Code'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'IP_Addr'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPAddr_a[0]);
		EDIT_SetText(hItem,buf);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_21);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPAddr_a[1]);
		EDIT_SetText(hItem,buf);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_22);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPAddr_a[2]);
		EDIT_SetText(hItem,buf);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_23);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPAddr_a[3]);
		EDIT_SetText(hItem,buf);
    // Initialization of 'Subnet_Mask'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPMask_a[0]);
		EDIT_SetText(hItem,buf);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_27);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPMask_a[1]);
		EDIT_SetText(hItem,buf);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_28);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPMask_a[2]);
		EDIT_SetText(hItem,buf);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_29);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPMask_a[3]);
		EDIT_SetText(hItem,buf);
    // Initialization of 'Gateway'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPGateway_a[0]);
		EDIT_SetText(hItem,buf);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_30);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPGateway_a[1]);
		EDIT_SetText(hItem,buf);		
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_31);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPGateway_a[2]);
		EDIT_SetText(hItem,buf);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_32);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucIPGateway_a[3]);
		EDIT_SetText(hItem,buf);		
    // Initialization of 'Port'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usDstIPPort);
		EDIT_SetText(hItem,buf);		
    // Initialization of 'Commucate_Addr'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucComAddr);
		EDIT_SetText(hItem,buf);
    // Initialization of 'Remote_IP'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_12);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usDstIPAddr_a[0]);
		EDIT_SetText(hItem,buf);	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_24);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usDstIPAddr_a[1]);
		EDIT_SetText(hItem,buf);		
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_25);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usDstIPAddr_a[2]);
		EDIT_SetText(hItem,buf);		
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_26);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usDstIPAddr_a[3]);
		EDIT_SetText(hItem,buf);				
    // Initialization of 'Baud_Rate'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
		DROPDOWN_SetFont(hItem,&GUI_Fontsongti15);
    DROPDOWN_AddString(hItem, "1200"); 
		DROPDOWN_AddString(hItem, "4800");
		DROPDOWN_AddString(hItem, "9600");
		DROPDOWN_AddString(hItem, "19200");
		DROPDOWN_AddString(hItem, "38400");
		if(Optimset_st.usComBaud==1200)
		DROPDOWN_SetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0),0);
		else if(Optimset_st.usComBaud==4800)
		DROPDOWN_SetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0),1);
		else if(Optimset_st.usComBaud==9600)
		DROPDOWN_SetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0),2);
		else if(Optimset_st.usComBaud==19200)
		DROPDOWN_SetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0),3);
		else if(Optimset_st.usComBaud==38400)
		DROPDOWN_SetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0),4);
		
    DROPDOWN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // Initialization of 'Device_Code_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"设备标识码");
    // Initialization of 'Commucate_Addr_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"设备通信地址");
    // Initialization of 'Baud_Rate_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"通信波特率");
    // Initialization of 'Remote_IP_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"远程IP地址");
    // Initialization of 'IP_Addr_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"本机IP地址");
    // Initialization of 'Subnet_Mask_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"子网掩码");
    // Initialization of 'Gateway_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"网关");
    // Initialization of ''Port_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"远程端口");
    // Initialization of 'V_Low_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"欠压阈值(V)");
    // Initialization of 'I_High1_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"一级过流阈值(%)");
    // Initialization of 'Frequency_Low_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"二级过流阈值(%)");
		// Initialization of 'Device_Code'
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		EDIT_SetFont(hItem,&GUI_Font16_1);
		sprintf(buf,"%X",FramFrm_CID1);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'V_Low'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_13);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usUVThr);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'I_High1'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_14);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucOCThrFst);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'Frequency_Low'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_15);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.ucOCThrSec);
		EDIT_SetText(hItem,buf);	
		    // Initialization of 'Pa_Threshold'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_16);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st. usOPThr[0]);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'Pb_Threshold'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_20);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st. usOPThr[1]);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'V_High'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_17);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usOVThr);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'I_High2'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_18);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usUFThr);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'Frequency_High'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_19);
		EDIT_SetFont(hItem,&GUI_Fontsongti15);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		sprintf(buf,"%d",Optimset_st.usOFThr);
		EDIT_SetText(hItem,buf);	
    // Initialization of 'Pa_Threshold_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"A路功率阈值(KW)");
    // Initialization of 'Pb_Threshold_Text'
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"B路功率阈值(KW)");
    // Initialization of 'V_High_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"过压阈值(V)");
    // Initialization of 'Frequency_High_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"过频阈值(Hz)");
    // Initialization of 'I_High2_Text'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_Fontsongti15);
		TEXT_SetTextColor(hItem,GUI_BLUE_98);
		TEXT_SetText(hItem,"欠频阈值(Hz)");	
		for(int i=0;i<12;i++)
		{
			hItem=WM_GetDialogItem(pMsg->hWin, ID_TEXT_24+i);
			TEXT_SetTextAlign(hItem,GUI_TA_BOTTOM);
		}	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
		BUTTON_SetText(hItem,"设置");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
		BUTTON_SetText(hItem,"返回");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem,&GUI_Fontsongti15);
		BUTTON_SetText(hItem,"帮助");
		BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,GUI_BLACK);
		if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
		{
			for (i = 0; i < 33; i++) 
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1+ i);  /* Get the handle of the edit widget */
				EDIT_SetFocussable(hItem,1);
				if(User_login==0x00)
					EDIT_SetFocussable(hItem,0);
			}
	  }
    break;		
		case WM_PAINT:
			GUI_SetColor(GUI_LIGHTBLUE);
			GUI_FillRect(0,0,480,20);
		  GUI_SetColor(GUI_LIGHTBLUE);
		  GUI_FillRect(0,260,480,272);
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			if(Optimset_st.Setup.Setup_st.bBusMode==BusModeD) 
			{
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-D",100,3);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_20);
       	EDIT_SetFocussable(hItem,0);
				EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,GUI_LIGHTGRAY);
			}
		  else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS) 
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-S",100,3);
		  else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeY) 
			{
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-Y",100,3);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_20);
       	EDIT_SetFocussable(hItem,0);
				EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,GUI_LIGHTGRAY);
			}
		  else if(Optimset_st.Setup.Setup_st.bBusMode==BusModeH)
			{
				GUI_DispStringAt("交流配电监测单元DPJ-G1K-H",100,3);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_20);
       	EDIT_SetFocussable(hItem,0);
				EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,GUI_LIGHTGRAY);
			}
	
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Font13_1);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			GUI_DispStringAt(SoftVersion,5,4);
			
			GUI_SetColor(GUI_WHITE);
			GUI_SetFont(&GUI_Fontsongti15);
			GUI_SetTextMode(GUI_TEXTMODE_TRANS);
			GUI_DispStringAt("设备信息",400,3);	
	  break;	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
		switch (NCode){
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:  
					if((Id>=ID_EDIT_1)&&(Id <= ID_EDIT_32))
					{
						if((User_login==0xFF)||(User_login==0xCC))
						{
			       if(Keyboard_Call==0) 
						 hPage[13] = CreateWindowNumberpad(hPage[9]);
              EDIT_SetText(WM_GetDialogItem(pMsg->hWin, Id),"");
							WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
							Keyboard_Call+=1;
						}	 
						 else
							 hPage[12] = CreateWindowKeypad(hPage[9]);									
					}	   				
					switch(Id) {
						case ID_BUTTON_0: // Notifications sent by 'Help'	
							  Window_Help_call=0x12;
							  WM_DeleteWindow(hPage[9]);	
                hPage[20]= CreateWindow_Help(WM_HBKWIN);
								WM_ShowWindow(hPage[20]);
							break;
						case ID_BUTTON_1: // Notifications sent by 'Back'
							if(Optimset_st.Setup.Setup_st.bBusMode==BusModeS)
							{
								WM_DeleteWindow(hPage[9]);
								hPage[8] = CreateWindowSystem_ConS(WM_HBKWIN);
								WM_ShowWindow(hPage[8]);
							}
							else 
							{
								WM_DeleteWindow(hPage[9]);
								hPage[18] = CreateWindowSystem_ConD(WM_HBKWIN);
								WM_ShowWindow(hPage[18]);
							}
							break;
						case ID_BUTTON_2: // Notifications sent by 'Set'
			
					   EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), buf, sizeof(buf));  //年
						 sDate.Year = atoi(buf);
				     EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1), buf, sizeof(buf));  //月
             sDate.Month = atoi(buf);
             EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2), buf, sizeof(buf));  //日
             sDate.Date= atoi(buf);
						 sDate.WeekDay=RTC_WEEKDAY_SATURDAY;
			       EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_3), buf, sizeof(buf));  //时
             sTime.Hours= atoi(buf);
				     EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_4), buf, sizeof(buf));  //分
             sTime.Minutes= atoi(buf);
				     EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_5), buf, sizeof(buf));  //秒
             sTime.Seconds= atoi(buf);
						 sTime.TimeFormat = RTC_HOURFORMAT12_AM;
						 sTime.DayLightSaving = RTC_DAYLIGHTSAVING_NONE;
						 sTime.StoreOperation = RTC_STOREOPERATION_RESET;
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_7), buf, sizeof(buf));  //本地IP
						 Optimset_st.ucIPAddr_a[0]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_21), buf, sizeof(buf)); 
						 Optimset_st.ucIPAddr_a[1]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_22), buf, sizeof(buf)); 
						 Optimset_st.ucIPAddr_a[2]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_23), buf, sizeof(buf));  
						 Optimset_st.ucIPAddr_a[3]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_8), buf, sizeof(buf));  //子网掩码
						 Optimset_st.ucIPMask_a[0]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_27), buf, sizeof(buf));  
						 Optimset_st.ucIPMask_a[1]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_28), buf, sizeof(buf));  
						 Optimset_st.ucIPMask_a[2]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_29), buf, sizeof(buf));  
						 Optimset_st.ucIPMask_a[3]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_9), buf, sizeof(buf));  //网关
						 Optimset_st.ucIPGateway_a[0]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_30), buf, sizeof(buf));  
						 Optimset_st.ucIPGateway_a[1]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_31), buf, sizeof(buf));  
						 Optimset_st.ucIPGateway_a[2]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_32), buf, sizeof(buf));  
						 Optimset_st.ucIPGateway_a[3]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_12), buf, sizeof(buf)); //远程IP 		
						 Optimset_st.usDstIPAddr_a[0]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_24), buf, sizeof(buf)); 		
						 Optimset_st.usDstIPAddr_a[1]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_25), buf, sizeof(buf)); 		
						 Optimset_st.usDstIPAddr_a[2]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_26), buf, sizeof(buf));  		
						 Optimset_st.usDstIPAddr_a[3]=atoi(buf);
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_10), buf, sizeof(buf));   //远程端口
						 Optimset_st.usDstIPPort= atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_11), buf, sizeof(buf));   //通信地址
						 Optimset_st.ucComAddr= atoi(buf); 					
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_13), buf, sizeof(buf));   //欠压阈值
						 Optimset_st.usUVThr= atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_14), buf, sizeof(buf));   //一级过流阈值
						 Optimset_st.ucOCThrFst= atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_15), buf, sizeof(buf));   //二级过流阈值
						 Optimset_st.ucOCThrSec= atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_17), buf, sizeof(buf));   //过压阈值
						 Optimset_st.usOVThr= atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_18), buf, sizeof(buf));   //欠频阈值
						 Optimset_st.usUFThr= atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_19), buf, sizeof(buf));   //过频阈值
						 Optimset_st.usOFThr= atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_16), buf, sizeof(buf));   //A路功率阈值
						 Optimset_st. usOPThr[0]=atoi(buf); 
						 EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_20), buf, sizeof(buf));   //B路功率阈值
						 Optimset_st. usOPThr[1]=atoi(buf); 
						 DropdownSecItemNum=DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0)); //波特率
						 if(DropdownSecItemNum==0) Optimset_st.usComBaud=1200;
						 if(DropdownSecItemNum==1) Optimset_st.usComBaud=4800;
						 if(DropdownSecItemNum==2) Optimset_st.usComBaud=9600;
						 if(DropdownSecItemNum==3) Optimset_st.usComBaud=19200;
						 if(DropdownSecItemNum==4) Optimset_st.usComBaud=38400;
						 Opt_Save();
             if(sDate.Year !=0 && sDate.Month!=0 && sDate.Date!=0)	
						 {							 
               HAL_RTC_SetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
               HAL_RTC_SetDate(&hrtc, &sDate, RTC_FORMAT_BIN);
						 }							 
					break;
	    }
			break;	
		 }
    break;		
	case WM_TIMER:
		Caculate_RTC(pMsg,ID_TEXT_23,ID_TEXT_22);		
    WM_RestartTimer(pMsg->Data.v, 100);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindowDevice_Inform(WM_HWIN hParent);
WM_HWIN CreateWindowDevice_Inform(WM_HWIN hParent) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_DeviceInform, GUI_COUNTOF(_DeviceInform), _cbDevice_Inform, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),0,200,0);
  return hWin;
}


/*************************** End of file ****************************/
